/**
 * Join the matching dots up without crossing, and fill the board.
 *
 * The one of the three that cannot be generated by scattering dots about and
 * hoping. Pick pairs at random and most boards have no answer at all, a few
 * have one, and nothing on the screen tells you which kind you have been
 * handed — so a child sits there for ten minutes being wrong about a board
 * that was wrong first.
 *
 * So it is built backwards, from an answer that exists before the puzzle does:
 *
 *   1. Make a Hamiltonian cycle — a single loop through every square of the
 *      grid exactly once. On a grid with even sides there is a construction
 *      for this: take any spanning tree of the half-sized grid, and trace
 *      round the outside of it. The loop it draws visits all four squares
 *      behind each half-square and never crosses itself.
 *   2. Cut the loop into as many arcs as there are colours.
 *   3. Show only the two ends of each arc.
 *
 * Every arc is a path, together they cover every square, and none of them
 * crosses another — because they were one loop a moment ago. The answer is
 * kept, so the board can be finished for somebody who has had enough.
 *
 * It does not promise the answer is the *only* one, and neither does the game
 * it is copied from: a board with a second way through is a board somebody
 * solved their own way, which is not a complaint anybody has ever made.
 */
import type { Rng } from '../engine/rng'

export interface Flow {
  across: number
  down: number
  /** For each colour, the two squares its dots are on. */
  ends: [number, number][]
  /** For each colour, the whole path between them. */
  answer: number[][]
}

/**
 * A loop through every square, from a spanning tree of the half-grid.
 *
 * Each square of the half-grid stands for a 2x2 block of the real one. The
 * loop runs round the tree like a piece of string laid round a shrub: along
 * one side of every branch and back along the other.
 */
function loopOf(across: number, down: number, rng: Rng): number[] {
  const wide = across / 2
  const tall = down / 2

  // A random spanning tree of the half-grid, depth first.
  const linked = new Set<string>()
  const name = (a: number, b: number) => (a < b ? `${a}:${b}` : `${b}:${a}`)
  const seen = new Array<boolean>(wide * tall).fill(false)
  const stack = [0]
  seen[0] = true
  while (stack.length > 0) {
    const here = stack[stack.length - 1]
    const x = here % wide
    const y = Math.floor(here / wide)
    const open: number[] = []
    if (x > 0 && !seen[here - 1]) open.push(here - 1)
    if (x < wide - 1 && !seen[here + 1]) open.push(here + 1)
    if (y > 0 && !seen[here - wide]) open.push(here - wide)
    if (y < tall - 1 && !seen[here + wide]) open.push(here + wide)
    if (open.length === 0) { stack.pop(); continue }
    const there = rng.pick(open)
    linked.add(name(here, there))
    seen[there] = true
    stack.push(there)
  }

  /*
   * Walk the loop.
   *
   * Standing on one of the four squares behind a half-square and facing a
   * direction, the next step is decided by whether the tree has a branch that
   * way: if it does, step across into the next block; if it does not, turn and
   * follow the wall round. Right-hand-on-the-wall, with the tree as the wall.
   */
  const at = (x: number, y: number) => y * across + x
  const joined = (hx: number, hy: number, dx: number, dy: number): boolean => {
    const tx = hx + dx
    const ty = hy + dy
    if (tx < 0 || tx >= wide || ty < 0 || ty >= tall) return false
    return linked.has(name(hy * wide + hx, ty * wide + tx))
  }

  /*
   * The four corners of a block, and the one rule at each.
   *
   * Left to itself a block is a little clockwise loop of its own four squares:
   * top-left to top-right to bottom-right to bottom-left and back. A branch of
   * the tree breaks that loop open in one place and the string goes round the
   * branch instead — so at each corner there is exactly one question, "is
   * there a branch this way", and the answer decides everything.
   *
   *     corner         carry on if a branch goes   otherwise
   *     top-left       up                          right
   *     top-right      right                       down
   *     bottom-right   down                        left
   *     bottom-left    left                        up
   *
   * The first cut of this kept a heading and turned right when it was not
   * leaving the block, which is the same thing three quarters of the time and
   * produced a loop four squares long.
   */
  const CORNERS = [
    // Indexed by iy * 2 + ix.
    { out: { x: 0, y: -1 }, on: { x: 1, y: 0 } },   // top-left
    { out: { x: 1, y: 0 }, on: { x: 0, y: 1 } },    // top-right
    { out: { x: -1, y: 0 }, on: { x: 0, y: -1 } },  // bottom-left
    { out: { x: 0, y: 1 }, on: { x: -1, y: 0 } },   // bottom-right
  ]

  const path: number[] = []
  let x = 0
  let y = 0
  const cells = across * down
  for (let step = 0; step < cells + 1 && path.length < cells; step++) {
    path.push(at(x, y))
    const hx = Math.floor(x / 2)
    const hy = Math.floor(y / 2)
    const corner = CORNERS[(y % 2) * 2 + (x % 2)]
    const go = joined(hx, hy, corner.out.x, corner.out.y) ? corner.out : corner.on
    x += go.x
    y += go.y
  }
  return path
}

/** The loop, cut into `colours` arcs, with only the ends shown. */
export function newFlow(across: number, down: number, colours: number, rng: Rng): Flow {
  const loop = loopOf(across, down, rng)
  const cells = across * down

  /*
   * Cut points, spread out rather than purely random.
   *
   * A random set of cuts gives one arc of twenty squares and three of one, and
   * a board with three dots already touching their partners is a board that is
   * most of the way solved before anybody looks at it.
   */
  const least = Math.max(2, Math.floor(cells / (colours * 2)))
  const cuts: number[] = [0]
  let at = 0
  for (let i = 1; i < colours; i++) {
    const room = cells - at - least * (colours - i)
    const step = Math.max(least, least + rng.int(0, Math.max(0, room - least)))
    at = Math.min(cells - least * (colours - i), at + step)
    cuts.push(at)
  }
  cuts.push(cells)

  const answer: number[][] = []
  for (let i = 0; i < colours; i++) {
    const arc = loop.slice(cuts[i], cuts[i + 1])
    if (arc.length > 0) answer.push(arc)
  }
  return {
    across,
    down,
    ends: answer.map((arc) => [arc[0], arc[arc.length - 1]] as [number, number]),
    answer,
  }
}

/** Whether two squares are side by side on the grid. */
export function touching(flow: { across: number }, a: number, b: number): boolean {
  const ax = a % flow.across
  const bx = b % flow.across
  const ay = Math.floor(a / flow.across)
  const by = Math.floor(b / flow.across)
  return Math.abs(ax - bx) + Math.abs(ay - by) === 1
}
