/**
 * Geography.
 *
 * The flag questions come in both directions on purpose: here is a flag, whose
 * is it, and here is a country, which of these four flags is its. The second
 * is much harder, because recognising something is easier than picking it out
 * of a line-up, and it is the direction that actually teaches you the flag.
 *
 * Capitals are a memory test and nothing else, so there are only a few, and
 * most of the rest are questions where the answer can be reasoned towards: why
 * a river is where it is, why a desert is a desert, why the lines on a map are
 * shaped the way they are.
 */
import type { Ask } from '../types'

export const GEOGRAPHY: readonly Ask[] = [
  // --- whose flag is this? -------------------------------------------------
  {
    id: 'g-flag-japan',
    topic: 'geography',
    rating: 700,
    prompt: 'Whose flag is this?',
    flag: 'japan',
    options: ['Japan', 'South Korea', 'Bangladesh', 'Switzerland'],
    explain: 'Japan. The red disc is the sun — the country’s name in Japanese means something close to "origin of the sun".',
  },
  {
    id: 'g-flag-brazil',
    topic: 'geography',
    rating: 800,
    prompt: 'Whose flag is this?',
    flag: 'brazil',
    options: ['Brazil', 'Portugal', 'Argentina', 'Nigeria'],
    explain: 'Brazil. The blue globe carries the night sky over Rio as it looked on one particular night in 1889.',
  },
  {
    id: 'g-flag-canada',
    topic: 'geography',
    rating: 750,
    prompt: 'Whose flag is this?',
    flag: 'canada',
    options: ['Canada', 'Peru', 'Austria', 'Denmark'],
    explain: 'Canada. The maple leaf has eleven points, chosen because it stayed clear when the flag was flapping.',
  },
  {
    id: 'g-flag-india',
    topic: 'geography',
    rating: 800,
    prompt: 'Whose flag is this?',
    flag: 'india',
    options: ['India', 'Ireland', 'Italy', 'Niger'],
    explain: 'India. The wheel in the middle is the Ashoka chakra, from a pillar carved over 2,000 years ago, and it has 24 spokes.',
  },
  {
    id: 'g-flag-vietnam',
    topic: 'geography',
    rating: 900,
    prompt: 'Whose flag is this?',
    flag: 'vietnam',
    options: ['Vietnam', 'China', 'Turkey', 'Morocco'],
    explain: 'Vietnam — one yellow star on red. China’s flag is also red with yellow stars, but it has five of them.',
  },
  {
    id: 'g-flag-turkey',
    topic: 'geography',
    rating: 950,
    prompt: 'Whose flag is this?',
    flag: 'turkey',
    options: ['Turkey', 'Tunisia', 'Pakistan', 'Algeria'],
    explain: 'Turkey. Several countries use a crescent and star; Turkey’s sits on plain red with the star off to one side.',
  },
  {
    id: 'g-flag-greece',
    topic: 'geography',
    rating: 1000,
    prompt: 'Whose flag is this?',
    flag: 'greece',
    options: ['Greece', 'Uruguay', 'Israel', 'Finland'],
    explain: 'Greece. The nine stripes are usually said to stand for the nine syllables of a Greek battle cry for freedom.',
  },
  {
    id: 'g-flag-sweden',
    topic: 'geography',
    rating: 850,
    prompt: 'Whose flag is this?',
    flag: 'sweden',
    options: ['Sweden', 'Denmark', 'Finland', 'Norway'],
    explain: 'Sweden. All five Nordic countries use an off-centre cross; Sweden’s is yellow on blue.',
  },
  {
    id: 'g-flag-czechia',
    topic: 'geography',
    rating: 1100,
    prompt: 'Whose flag is this?',
    flag: 'czechia',
    options: ['Czechia', 'Poland', 'Philippines', 'Jordan'],
    explain: 'Czechia. It was Czechoslovakia’s flag, and when the country split in 1993 the Czechs kept it.',
  },
  {
    id: 'g-flag-uk',
    topic: 'geography',
    rating: 900,
    prompt: 'Whose flag is this?',
    flag: 'uk',
    options: ['United Kingdom', 'Norway', 'Iceland', 'Australia'],
    explain: 'The United Kingdom. It is three flags stacked: the crosses of England, Scotland and Ireland laid over each other.',
  },
  {
    id: 'g-flag-jamaica',
    topic: 'geography',
    rating: 1050,
    prompt: 'Whose flag is this?',
    flag: 'jamaica',
    options: ['Jamaica', 'Congo', 'Tanzania', 'Namibia'],
    explain: 'Jamaica — for a long time the only national flag with no red, white or blue anywhere on it.',
  },
  {
    id: 'g-flag-argentina',
    topic: 'geography',
    rating: 1000,
    prompt: 'Whose flag is this?',
    flag: 'argentina',
    options: ['Argentina', 'Greece', 'Guatemala', 'Uruguay'],
    explain: 'Argentina. The golden face in the middle is the Sun of May.',
  },
  {
    id: 'g-flag-portugal',
    topic: 'geography',
    rating: 1100,
    prompt: 'Whose flag is this?',
    flag: 'portugal',
    options: ['Portugal', 'Italy', 'Brazil', 'Mexico'],
    explain: 'Portugal. The circle is an armillary sphere, an instrument for modelling the sky, from its age of ocean voyages.',
  },

  // --- which flag is theirs? -----------------------------------------------
  {
    id: 'g-which-japan',
    topic: 'geography',
    rating: 800,
    prompt: 'Which of these is the flag of Japan?',
    showFlags: true,
    options: ['Japan', 'Bangladesh', 'Switzerland', 'Turkey'],
    explain: 'A red disc, centred, on white. Bangladesh has a red disc too, but on green and slightly left of centre.',
  },
  {
    id: 'g-which-italy',
    topic: 'geography',
    rating: 950,
    prompt: 'Which of these is the flag of Italy?',
    showFlags: true,
    options: ['Italy', 'Ireland', 'France', 'Belgium'],
    explain: 'Green, white and red, upright. Ireland’s is the same shape but ends in orange, not red.',
  },
  {
    id: 'g-which-germany',
    topic: 'geography',
    rating: 900,
    prompt: 'Which of these is the flag of Germany?',
    showFlags: true,
    options: ['Germany', 'Belgium', 'Netherlands', 'Austria'],
    explain: 'Black, red and gold in bands across. Belgium uses the same three colours but stands them upright.',
  },
  {
    id: 'g-which-norway',
    topic: 'geography',
    rating: 1150,
    prompt: 'Which of these is the flag of Norway?',
    showFlags: true,
    options: ['Norway', 'Iceland', 'Denmark', 'Finland'],
    explain: 'A blue cross inside a white cross on red. Iceland is the same idea with the red and blue swapped.',
  },
  {
    id: 'g-which-usa',
    topic: 'geography',
    rating: 750,
    prompt: 'Which of these is the flag of the United States?',
    showFlags: true,
    options: ['United States', 'Chile', 'Cuba', 'Greece'],
    explain: 'Thirteen stripes for the first thirteen states, and a star for every state there is now.',
  },
  {
    id: 'g-which-india',
    topic: 'geography',
    rating: 900,
    prompt: 'Which of these is the flag of India?',
    showFlags: true,
    options: ['India', 'Ireland', 'Italy', 'Nigeria'],
    explain: 'Saffron, white and green in bands across, with the navy chakra in the middle.',
  },
  {
    id: 'g-which-china',
    topic: 'geography',
    rating: 850,
    prompt: 'Which of these is the flag of China?',
    showFlags: true,
    options: ['China', 'Vietnam', 'Turkey', 'Japan'],
    explain: 'One big star with four smaller ones curving beside it, all in the top corner.',
  },
  {
    id: 'g-which-canada',
    topic: 'geography',
    rating: 800,
    prompt: 'Which of these is the flag of Canada?',
    showFlags: true,
    options: ['Canada', 'Peru', 'Austria', 'Poland'],
    explain: 'Red, white, red upright, with the maple leaf in the middle. Peru has the same bands and no leaf.',
  },

  // --- capitals ------------------------------------------------------------
  {
    id: 'g-cap-australia',
    topic: 'geography',
    rating: 1000,
    prompt: 'What is the capital of Australia?',
    options: ['Canberra', 'Sydney', 'Melbourne', 'Perth'],
    explain: 'Sydney and Melbourne both wanted it, so in 1908 a new city was built between them and given the job.',
  },
  {
    id: 'g-cap-brazil',
    topic: 'geography',
    rating: 1050,
    prompt: 'What is the capital of Brazil?',
    options: ['Brasília', 'Rio de Janeiro', 'São Paulo', 'Salvador'],
    explain: 'Built from nothing in the empty middle of the country in the 1950s, to pull people inland from the coast.',
  },
  {
    id: 'g-cap-turkey',
    topic: 'geography',
    rating: 1100,
    prompt: 'What is the capital of Turkey?',
    options: ['Ankara', 'Istanbul', 'Izmir', 'Antalya'],
    explain: 'Istanbul is much bigger and much older, but the capital moved to Ankara in 1923.',
  },
  {
    id: 'g-cap-canada',
    topic: 'geography',
    rating: 950,
    prompt: 'What is the capital of Canada?',
    options: ['Ottawa', 'Toronto', 'Vancouver', 'Montreal'],
    explain: 'Chosen partly because it sat on the line between the English-speaking and French-speaking halves of the country.',
  },
  {
    id: 'g-cap-south-africa',
    topic: 'geography',
    rating: 1300,
    prompt: 'How many capital cities does South Africa have?',
    options: ['Three', 'One', 'Two', 'Four'],
    explain: 'Pretoria governs, Cape Town makes the laws, and Bloemfontein holds the highest court.',
  },
  {
    id: 'g-cap-japan',
    topic: 'geography',
    rating: 700,
    prompt: 'What is the capital of Japan?',
    options: ['Tokyo', 'Kyoto', 'Osaka', 'Nagoya'],
    explain: 'Kyoto held it for over a thousand years before it moved to Tokyo in 1868. Tokyo’s old name was Edo.',
  },
  {
    id: 'g-cap-egypt',
    topic: 'geography',
    rating: 800,
    prompt: 'What is the capital of Egypt?',
    options: ['Cairo', 'Alexandria', 'Luxor', 'Giza'],
    explain: 'Cairo sits where the Nile fans out into its delta, which is why it grew there.',
  },

  // --- the shape of the world ----------------------------------------------
  {
    id: 'g-longest-river',
    topic: 'geography',
    rating: 900,
    prompt: 'Which two rivers are usually named as the longest in the world?',
    options: ['The Nile and the Amazon', 'The Thames and the Danube', 'The Ganges and the Rhine', 'The Volga and the Seine'],
    explain: 'They are so close that it depends where you say the Amazon starts, and the argument is still going.',
  },
  {
    id: 'g-sahara',
    topic: 'geography',
    rating: 1050,
    prompt: 'Why is the Sahara a desert?',
    options: [
      'Air sinking there is dry, so clouds rarely form',
      'It is too far from any sea',
      'It is too hot for rain',
      'The sand soaks up the rain',
    ],
    explain: 'It sits under a band of sinking air around 30° north. Most of the world’s big deserts sit in the same two bands.',
  },
  {
    id: 'g-antarctica-desert',
    topic: 'geography',
    rating: 1250,
    prompt: 'Which is the largest desert on Earth?',
    options: ['Antarctica', 'The Sahara', 'The Gobi', 'The Arabian desert'],
    explain: 'A desert is defined by how little falls from the sky, not by heat. Antarctica gets almost none.',
  },
  {
    id: 'g-everest',
    topic: 'geography',
    rating: 850,
    prompt: 'Which mountain range is Everest in?',
    options: ['The Himalayas', 'The Andes', 'The Alps', 'The Rockies'],
    explain: 'The Himalayas are still rising, because India is still pushing north into Asia.',
  },
  {
    id: 'g-andes',
    topic: 'geography',
    rating: 1000,
    prompt: 'Which is the longest mountain range on land?',
    options: ['The Andes', 'The Himalayas', 'The Rockies', 'The Alps'],
    explain: 'The Andes run about 7,000 km down the whole western edge of South America.',
  },
  {
    id: 'g-oceans',
    topic: 'geography',
    rating: 800,
    prompt: 'Which is the largest ocean?',
    options: ['The Pacific', 'The Atlantic', 'The Indian', 'The Arctic'],
    explain: 'It covers about a third of the planet — wider than all the land on Earth put together.',
  },
  {
    id: 'g-equator-countries',
    topic: 'geography',
    rating: 1150,
    prompt: 'Which of these countries does the equator run through?',
    options: ['Kenya', 'Egypt', 'India', 'Mexico'],
    explain: 'It crosses Kenya almost exactly in the middle. Ecuador is named after it.',
  },
  {
    id: 'g-russia-size',
    topic: 'geography',
    rating: 900,
    prompt: 'Which is the largest country in the world by area?',
    options: ['Russia', 'Canada', 'China', 'United States'],
    explain: 'It spans eleven time zones. When it is breakfast at one end it is evening at the other.',
  },
  {
    id: 'g-most-people',
    topic: 'geography',
    rating: 950,
    prompt: 'Which continent has the most people living on it?',
    options: ['Asia', 'Africa', 'Europe', 'South America'],
    explain: 'About three in every five people on Earth live in Asia.',
  },
  {
    id: 'g-nile-direction',
    topic: 'geography',
    rating: 1200,
    prompt: 'The Nile flows north, towards the Mediterranean. Why does that surprise people?',
    options: [
      'They expect rivers to flow down the map',
      'Rivers cannot flow north',
      'The Mediterranean is higher',
      'It changes direction in summer',
    ],
    explain: 'Water flows downhill, not down the page. The land at the Nile’s source is simply higher than the land at its mouth.',
  },
  {
    id: 'g-landlocked',
    topic: 'geography',
    rating: 1100,
    prompt: 'What does it mean for a country to be landlocked?',
    options: [
      'It has no coastline at all',
      'It is surrounded by mountains',
      'It has no rivers',
      'It has closed its borders',
    ],
    explain: 'About one country in five is. Two of them — Uzbekistan and Liechtenstein — are surrounded only by other landlocked countries.',
  },
  {
    id: 'g-timezones',
    topic: 'geography',
    rating: 1250,
    prompt: 'Why does the world have time zones at all?',
    options: [
      'Noon happens at different moments in different places',
      'To make trains easier to build',
      'Because clocks run at different speeds',
      'Because the Earth is tilted',
    ],
    explain: 'The sun is overhead somewhere different every minute. Before railways every town kept its own noon, and it did not matter.',
  },
  {
    id: 'g-plates',
    topic: 'geography',
    rating: 1150,
    prompt: 'Why does Iceland have so many volcanoes and hot springs?',
    options: [
      'It sits on the join between two plates that are pulling apart',
      'It is close to the Arctic',
      'It is a very young island',
      'It has no rivers to cool it',
    ],
    explain: 'The Mid-Atlantic Ridge runs straight through it, and the island is being pulled slightly wider every year.',
  },
  {
    id: 'g-amazon-rain',
    topic: 'geography',
    rating: 1200,
    prompt: 'The Amazon rainforest is sometimes called a river in the sky. Why?',
    options: [
      'The trees breathe out water that falls as rain elsewhere',
      'It has more rivers than anywhere',
      'It floods every year',
      'Clouds form only above it',
    ],
    explain: 'The forest lifts enormous amounts of water into the air, and much of South America’s rain comes back down from it.',
  },
  {
    id: 'g-city-highest',
    topic: 'geography',
    rating: 1300,
    prompt: 'Cooking a potato takes longer in La Paz, Bolivia, than at the seaside. Why?',
    options: [
      'Water boils at a lower temperature up there',
      'The potatoes are harder',
      'The air is colder',
      'There is less oxygen for the fire',
    ],
    explain: 'At 3,600 m the air pushes down less, so water boils at about 88 °C — and boiling water that is cooler cooks more slowly.',
  },
  {
    id: 'g-continent-count',
    topic: 'geography',
    rating: 1050,
    prompt: 'Why do different countries teach a different number of continents?',
    options: [
      'There is no rule that says where one ends and the next begins',
      'Some countries have not counted them',
      'New continents keep being found',
      'It depends on the map projection',
    ],
    explain: 'Europe and Asia are one piece of land. Some places teach five continents, some six, some seven, and none of them is wrong.',
  },
  {
    id: 'g-map-greenland',
    topic: 'geography',
    rating: 1250,
    prompt: 'On many world maps Greenland looks as big as Africa. How much of Africa is it really?',
    options: ['About a fourteenth', 'About half', 'About the same', 'About a quarter'],
    explain: 'Flattening a globe stretches whatever is near the poles. Africa is about fourteen times Greenland’s area.',
  },
  {
    id: 'g-strait',
    topic: 'geography',
    rating: 1150,
    prompt: 'What is a strait?',
    options: [
      'A narrow stretch of water joining two larger ones',
      'A straight stretch of coast',
      'A river with no bends',
      'A very deep harbour',
    ],
    explain: 'Gibraltar, Hormuz, Malacca. They are narrow, so whoever sits beside one has always mattered more than their size suggests.',
  },
  {
    id: 'g-seasons',
    topic: 'geography',
    rating: 1100,
    prompt: 'Why is it summer in Australia when it is winter in Europe?',
    options: [
      'The Earth is tilted, so the halves lean towards the sun in turn',
      'Australia is closer to the sun',
      'The Earth’s orbit is an oval',
      'The sun moves south in December',
    ],
    explain: 'The tilt is about 23 degrees and it stays pointing the same way all year, so each half takes its turn leaning sunward.',
  },
]
