/**
 * Geography.
 *
 * The flag questions come in both directions on purpose: here is a flag, whose
 * is it, and here is a country, which of these four flags is its. The second
 * is much harder, because recognising something is easier than picking it out
 * of a line-up, and it is the direction that actually teaches you the flag.
 *
 * Capitals are a memory test and nothing else, so there are only a few, and
 * most of the rest are questions where the answer can be reasoned towards: why
 * a river is where it is, why a desert is a desert, why the lines on a map are
 * shaped the way they are.
 */
import type { Ask } from '../types'

export const GEOGRAPHY: readonly Ask[] = [
  // --- whose flag is this? -------------------------------------------------
  {
    id: 'g-flag-japan',
    topic: 'geography',
    rating: 700,
    prompt: 'Whose flag is this?',
    flag: 'japan',
    options: ['Japan', 'South Korea', 'Bangladesh', 'Switzerland'],
    explain: 'Japan. The red disc is the sun — the country’s name in Japanese means something close to "origin of the sun".',
  },
  {
    id: 'g-flag-brazil',
    topic: 'geography',
    rating: 800,
    prompt: 'Whose flag is this?',
    flag: 'brazil',
    options: ['Brazil', 'Portugal', 'Argentina', 'Nigeria'],
    explain: 'Brazil. The blue globe carries the night sky over Rio as it looked on one particular night in 1889.',
  },
  {
    id: 'g-flag-canada',
    topic: 'geography',
    rating: 750,
    prompt: 'Whose flag is this?',
    flag: 'canada',
    options: ['Canada', 'Peru', 'Austria', 'Denmark'],
    explain: 'Canada. The maple leaf has eleven points, chosen because it stayed clear when the flag was flapping.',
  },
  {
    id: 'g-flag-india',
    topic: 'geography',
    rating: 800,
    prompt: 'Whose flag is this?',
    flag: 'india',
    options: ['India', 'Ireland', 'Italy', 'Niger'],
    explain: 'India. The wheel in the middle is the Ashoka chakra, from a pillar carved over 2,000 years ago, and it has 24 spokes.',
  },
  {
    id: 'g-flag-vietnam',
    topic: 'geography',
    rating: 900,
    prompt: 'Whose flag is this?',
    flag: 'vietnam',
    options: ['Vietnam', 'China', 'Turkey', 'Morocco'],
    explain: 'Vietnam — one yellow star on red. China’s flag is also red with yellow stars, but it has five of them.',
  },
  {
    id: 'g-flag-turkey',
    topic: 'geography',
    rating: 950,
    prompt: 'Whose flag is this?',
    flag: 'turkey',
    options: ['Turkey', 'Tunisia', 'Pakistan', 'Algeria'],
    explain: 'Turkey. Several countries use a crescent and star; Turkey’s sits on plain red with the star off to one side.',
  },
  {
    id: 'g-flag-greece',
    topic: 'geography',
    rating: 1000,
    prompt: 'Whose flag is this?',
    flag: 'greece',
    options: ['Greece', 'Uruguay', 'Israel', 'Finland'],
    explain: 'Greece. The nine stripes are usually said to stand for the nine syllables of a Greek battle cry for freedom.',
  },
  {
    id: 'g-flag-sweden',
    topic: 'geography',
    rating: 850,
    prompt: 'Whose flag is this?',
    flag: 'sweden',
    options: ['Sweden', 'Denmark', 'Finland', 'Norway'],
    explain: 'Sweden. All five Nordic countries use an off-centre cross; Sweden’s is yellow on blue.',
  },
  {
    id: 'g-flag-czechia',
    topic: 'geography',
    rating: 1100,
    prompt: 'Whose flag is this?',
    flag: 'czechia',
    options: ['Czechia', 'Poland', 'Philippines', 'Jordan'],
    explain: 'Czechia. It was Czechoslovakia’s flag, and when the country split in 1993 the Czechs kept it.',
  },
  {
    id: 'g-flag-uk',
    topic: 'geography',
    rating: 900,
    prompt: 'Whose flag is this?',
    flag: 'uk',
    options: ['United Kingdom', 'Norway', 'Iceland', 'Australia'],
    explain: 'The United Kingdom. It is three flags stacked: the crosses of England, Scotland and Ireland laid over each other.',
  },
  {
    id: 'g-flag-jamaica',
    topic: 'geography',
    rating: 1050,
    prompt: 'Whose flag is this?',
    flag: 'jamaica',
    options: ['Jamaica', 'Congo', 'Tanzania', 'Namibia'],
    explain: 'Jamaica — for a long time the only national flag with no red, white or blue anywhere on it.',
  },
  {
    id: 'g-flag-argentina',
    topic: 'geography',
    rating: 1000,
    prompt: 'Whose flag is this?',
    flag: 'argentina',
    options: ['Argentina', 'Greece', 'Guatemala', 'Uruguay'],
    explain: 'Argentina. The golden face in the middle is the Sun of May.',
  },
  {
    id: 'g-flag-portugal',
    topic: 'geography',
    rating: 1100,
    prompt: 'Whose flag is this?',
    flag: 'portugal',
    options: ['Portugal', 'Italy', 'Brazil', 'Mexico'],
    explain: 'Portugal. The circle is an armillary sphere, an instrument for modelling the sky, from its age of ocean voyages.',
  },

  // --- which flag is theirs? -----------------------------------------------
  {
    id: 'g-which-japan',
    topic: 'geography',
    rating: 800,
    prompt: 'Which of these is the flag of Japan?',
    showFlags: true,
    options: ['Japan', 'Bangladesh', 'Switzerland', 'Turkey'],
    explain: 'A red disc, centred, on white. Bangladesh has a red disc too, but on green and slightly left of centre.',
  },
  {
    id: 'g-which-italy',
    topic: 'geography',
    rating: 950,
    prompt: 'Which of these is the flag of Italy?',
    showFlags: true,
    options: ['Italy', 'Ireland', 'France', 'Belgium'],
    explain: 'Green, white and red, upright. Ireland’s is the same shape but ends in orange, not red.',
  },
  {
    id: 'g-which-germany',
    topic: 'geography',
    rating: 900,
    prompt: 'Which of these is the flag of Germany?',
    showFlags: true,
    options: ['Germany', 'Belgium', 'Netherlands', 'Austria'],
    explain: 'Black, red and gold in bands across. Belgium uses the same three colours but stands them upright.',
  },
  {
    id: 'g-which-norway',
    topic: 'geography',
    rating: 1150,
    prompt: 'Which of these is the flag of Norway?',
    showFlags: true,
    options: ['Norway', 'Iceland', 'Denmark', 'Finland'],
    explain: 'A blue cross inside a white cross on red. Iceland is the same idea with the red and blue swapped.',
  },
  {
    id: 'g-which-usa',
    topic: 'geography',
    rating: 750,
    prompt: 'Which of these is the flag of the United States?',
    showFlags: true,
    options: ['United States', 'Chile', 'Cuba', 'Greece'],
    explain: 'Thirteen stripes for the first thirteen states, and a star for every state there is now.',
  },
  {
    id: 'g-which-india',
    topic: 'geography',
    rating: 900,
    prompt: 'Which of these is the flag of India?',
    showFlags: true,
    options: ['India', 'Ireland', 'Italy', 'Nigeria'],
    explain: 'Saffron, white and green in bands across, with the navy chakra in the middle.',
  },
  {
    id: 'g-which-china',
    topic: 'geography',
    rating: 850,
    prompt: 'Which of these is the flag of China?',
    showFlags: true,
    options: ['China', 'Vietnam', 'Turkey', 'Japan'],
    explain: 'One big star with four smaller ones curving beside it, all in the top corner.',
  },
  {
    id: 'g-which-canada',
    topic: 'geography',
    rating: 800,
    prompt: 'Which of these is the flag of Canada?',
    showFlags: true,
    options: ['Canada', 'Peru', 'Austria', 'Poland'],
    explain: 'Red, white, red upright, with the maple leaf in the middle. Peru has the same bands and no leaf.',
  },

  // --- capitals ------------------------------------------------------------
  {
    id: 'g-cap-australia',
    topic: 'geography',
    rating: 1000,
    prompt: 'What is the capital of Australia?',
    options: ['Canberra', 'Sydney', 'Melbourne', 'Perth'],
    explain: 'Sydney and Melbourne both wanted it, so in 1908 a new city was built between them and given the job.',
  },
  {
    id: 'g-cap-brazil',
    topic: 'geography',
    rating: 1050,
    prompt: 'What is the capital of Brazil?',
    options: ['Brasília', 'Rio de Janeiro', 'São Paulo', 'Salvador'],
    explain: 'Built from nothing in the empty middle of the country in the 1950s, to pull people inland from the coast.',
  },
  {
    id: 'g-cap-turkey',
    topic: 'geography',
    rating: 1100,
    prompt: 'What is the capital of Turkey?',
    options: ['Ankara', 'Istanbul', 'Izmir', 'Antalya'],
    explain: 'Istanbul is much bigger and much older, but the capital moved to Ankara in 1923.',
  },
  {
    id: 'g-cap-canada',
    topic: 'geography',
    rating: 950,
    prompt: 'What is the capital of Canada?',
    options: ['Ottawa', 'Toronto', 'Vancouver', 'Montreal'],
    explain: 'Chosen partly because it sat on the line between the English-speaking and French-speaking halves of the country.',
  },
  {
    id: 'g-cap-south-africa',
    topic: 'geography',
    rating: 1300,
    prompt: 'How many capital cities does South Africa have?',
    options: ['Three', 'One', 'Two', 'Four'],
    explain: 'Pretoria governs, Cape Town makes the laws, and Bloemfontein holds the highest court.',
  },
  {
    id: 'g-cap-japan',
    topic: 'geography',
    rating: 700,
    prompt: 'What is the capital of Japan?',
    options: ['Tokyo', 'Kyoto', 'Osaka', 'Nagoya'],
    explain: 'Kyoto held it for over a thousand years before it moved to Tokyo in 1868. Tokyo’s old name was Edo.',
  },
  {
    id: 'g-cap-egypt',
    topic: 'geography',
    rating: 800,
    prompt: 'What is the capital of Egypt?',
    options: ['Cairo', 'Alexandria', 'Luxor', 'Giza'],
    explain: 'Cairo sits where the Nile fans out into its delta, which is why it grew there.',
  },

  // --- the shape of the world ----------------------------------------------
  {
    id: 'g-longest-river',
    topic: 'geography',
    rating: 900,
    prompt: 'Which two rivers are usually named as the longest in the world?',
    options: ['The Nile and the Amazon', 'The Thames and the Danube', 'The Ganges and the Rhine', 'The Volga and the Seine'],
    explain: 'They are so close that it depends where you say the Amazon starts, and the argument is still going.',
  },
  {
    id: 'g-sahara',
    topic: 'geography',
    rating: 1050,
    prompt: 'Why is the Sahara a desert?',
    options: [
      'Air sinking there is dry, so clouds rarely form',
      'It is too far from any sea',
      'It is too hot for rain',
      'The sand soaks up the rain',
    ],
    explain: 'It sits under a band of sinking air around 30° north. Most of the world’s big deserts sit in the same two bands.',
  },
  {
    id: 'g-antarctica-desert',
    topic: 'geography',
    rating: 1250,
    prompt: 'Which is the largest desert on Earth?',
    options: ['Antarctica', 'The Sahara', 'The Gobi', 'The Arabian desert'],
    explain: 'A desert is defined by how little falls from the sky, not by heat. Antarctica gets almost none.',
  },
  {
    id: 'g-everest',
    topic: 'geography',
    rating: 850,
    prompt: 'Which mountain range is Everest in?',
    options: ['The Himalayas', 'The Andes', 'The Alps', 'The Rockies'],
    explain: 'The Himalayas are still rising, because India is still pushing north into Asia.',
  },
  {
    id: 'g-andes',
    topic: 'geography',
    rating: 1000,
    prompt: 'Which is the longest mountain range on land?',
    options: ['The Andes', 'The Himalayas', 'The Rockies', 'The Alps'],
    explain: 'The Andes run about 7,000 km down the whole western edge of South America.',
  },
  {
    id: 'g-oceans',
    topic: 'geography',
    rating: 800,
    prompt: 'Which is the largest ocean?',
    options: ['The Pacific', 'The Atlantic', 'The Indian', 'The Arctic'],
    explain: 'It covers about a third of the planet — wider than all the land on Earth put together.',
  },
  {
    id: 'g-equator-countries',
    topic: 'geography',
    rating: 1150,
    prompt: 'Which of these countries does the equator run through?',
    options: ['Kenya', 'Egypt', 'India', 'Mexico'],
    explain: 'It crosses Kenya almost exactly in the middle. Ecuador is named after it.',
  },
  {
    id: 'g-russia-size',
    topic: 'geography',
    rating: 900,
    prompt: 'Which is the largest country in the world by area?',
    options: ['Russia', 'Canada', 'China', 'United States'],
    explain: 'It spans eleven time zones. When it is breakfast at one end it is evening at the other.',
  },
  {
    id: 'g-most-people',
    topic: 'geography',
    rating: 950,
    prompt: 'Which continent has the most people living on it?',
    options: ['Asia', 'Africa', 'Europe', 'South America'],
    explain: 'About three in every five people on Earth live in Asia.',
  },
  {
    id: 'g-nile-direction',
    topic: 'geography',
    rating: 1200,
    prompt: 'The Nile flows north, towards the Mediterranean. Why does that surprise people?',
    options: [
      'They expect rivers to flow down the map',
      'Rivers cannot flow north',
      'The Mediterranean is higher',
      'It changes direction in summer',
    ],
    explain: 'Water flows downhill, not down the page. The land at the Nile’s source is simply higher than the land at its mouth.',
  },
  {
    id: 'g-landlocked',
    topic: 'geography',
    rating: 1100,
    prompt: 'What does it mean for a country to be landlocked?',
    options: [
      'It has no coastline at all',
      'It is surrounded by mountains',
      'It has no rivers',
      'It has closed its borders',
    ],
    explain: 'About one country in five is. Two of them — Uzbekistan and Liechtenstein — are surrounded only by other landlocked countries.',
  },
  {
    id: 'g-timezones',
    topic: 'geography',
    rating: 1250,
    prompt: 'Why does the world have time zones at all?',
    options: [
      'Noon happens at different moments in different places',
      'To make trains easier to build',
      'Because clocks run at different speeds',
      'Because the Earth is tilted',
    ],
    explain: 'The sun is overhead somewhere different every minute. Before railways every town kept its own noon, and it did not matter.',
  },
  {
    id: 'g-plates',
    topic: 'geography',
    rating: 1150,
    prompt: 'Why does Iceland have so many volcanoes and hot springs?',
    options: [
      'It sits on the join between two plates that are pulling apart',
      'It is close to the Arctic',
      'It is a very young island',
      'It has no rivers to cool it',
    ],
    explain: 'The Mid-Atlantic Ridge runs straight through it, and the island is being pulled slightly wider every year.',
  },
  {
    id: 'g-amazon-rain',
    topic: 'geography',
    rating: 1200,
    prompt: 'The Amazon rainforest is sometimes called a river in the sky. Why?',
    options: [
      'The trees breathe out water that falls as rain elsewhere',
      'It has more rivers than anywhere',
      'It floods every year',
      'Clouds form only above it',
    ],
    explain: 'The forest lifts enormous amounts of water into the air, and much of South America’s rain comes back down from it.',
  },
  {
    id: 'g-city-highest',
    topic: 'geography',
    rating: 1300,
    prompt: 'Cooking a potato takes longer in La Paz, Bolivia, than at the seaside. Why?',
    options: [
      'Water boils at a lower temperature up there',
      'The potatoes are harder',
      'The air is colder',
      'There is less oxygen for the fire',
    ],
    explain: 'At 3,600 m the air pushes down less, so water boils at about 88 °C — and boiling water that is cooler cooks more slowly.',
  },
  {
    id: 'g-continent-count',
    topic: 'geography',
    rating: 1050,
    prompt: 'Why do different countries teach a different number of continents?',
    options: [
      'There is no rule that says where one ends and the next begins',
      'Some countries have not counted them',
      'New continents keep being found',
      'It depends on the map projection',
    ],
    explain: 'Europe and Asia are one piece of land. Some places teach five continents, some six, some seven, and none of them is wrong.',
  },
  {
    id: 'g-map-greenland',
    topic: 'geography',
    rating: 1250,
    prompt: 'On many world maps Greenland looks as big as Africa. How much of Africa is it really?',
    options: ['About a fourteenth', 'About half', 'About the same', 'About a quarter'],
    explain: 'Flattening a globe stretches whatever is near the poles. Africa is about fourteen times Greenland’s area.',
  },
  {
    id: 'g-strait',
    topic: 'geography',
    rating: 1150,
    prompt: 'What is a strait?',
    options: [
      'A narrow stretch of water joining two larger ones',
      'A straight stretch of coast',
      'A river with no bends',
      'A very deep harbour',
    ],
    explain: 'Gibraltar, Hormuz, Malacca. They are narrow, so whoever sits beside one has always mattered more than their size suggests.',
  },
  {
    id: 'g-seasons',
    topic: 'geography',
    rating: 1100,
    prompt: 'Why is it summer in Australia when it is winter in Europe?',
    options: [
      'The Earth is tilted, so the halves lean towards the sun in turn',
      'Australia is closer to the sun',
      'The Earth’s orbit is an oval',
      'The sun moves south in December',
    ],
    explain: 'The tilt is about 23 degrees and it stays pointing the same way all year, so each half takes its turn leaning sunward.',
  },
  // --- added when the bank had to last -------------------------------------
  //
  // A question answered correctly is never asked again now, which turns the
  // bank from a rotation into a supply. These are the second batch.
  {
    id: 'g-dead-sea',
    topic: 'geography',
    rating: 1000,
    prompt: 'Why can you float so easily in the Dead Sea?',
    options: [
      'It is so salty that the water is heavier than you',
      'It is very shallow',
      'It is warmer than other seas',
      'It has no waves',
    ],
    explain: 'About ten times saltier than the ocean. Dense water pushes back harder, so you sit on top of it like a cork.',
  },
  {
    id: 'g-sahara-size',
    topic: 'geography',
    rating: 950,
    prompt: 'Roughly how big is the Sahara?',
    options: ['About the size of the United States', 'About the size of France', 'About the size of India', 'About the size of Australia'],
    explain: 'Nine million square kilometres. It is not the biggest desert on Earth, though — Antarctica is, because a desert is about rainfall, not heat.',
  },
  {
    id: 'g-amazon-mouth',
    topic: 'geography',
    rating: 1050,
    prompt: 'What is unusual about the mouth of the Amazon?',
    options: [
      'It pushes fresh water a hundred miles out to sea',
      'It flows uphill',
      'It freezes in winter',
      'It has no delta at all',
    ],
    explain: 'It carries about a fifth of all the river water on Earth. Sailors used to refill their barrels out of sight of land.',
  },
  {
    id: 'g-russia-timezones',
    topic: 'geography',
    rating: 900,
    prompt: 'How many time zones does Russia cover?',
    options: ['Eleven', 'Three', 'Six', 'Twenty'],
    explain: 'When it is breakfast in Kaliningrad it is evening in Kamchatka, and both are the same country.',
  },
  {
    id: 'g-iceland-greenland',
    topic: 'geography',
    rating: 1050,
    prompt: 'Which is greener — Iceland or Greenland?',
    options: ['Iceland', 'Greenland', 'Both are the same', 'Neither has plants'],
    explain: 'Greenland is mostly ice. The story goes that it was named hopefully, to attract settlers.',
  },
  {
    id: 'g-mariana',
    topic: 'geography',
    rating: 1100,
    prompt: 'If you dropped Everest into the deepest part of the ocean, what would happen?',
    options: [
      'It would vanish with two kilometres of water to spare',
      'The peak would stick out',
      'It would just fit',
      'It would touch the bottom and the top together',
    ],
    explain: 'The Mariana Trench is about eleven kilometres deep. Everest is not quite nine.',
  },
  {
    id: 'g-tectonic',
    topic: 'geography',
    rating: 1100,
    prompt: 'Why is there a ring of volcanoes around the Pacific?',
    options: [
      'The plates carrying the ocean floor dive under the ones around it',
      'The Pacific is hotter than other oceans',
      'It is the oldest sea floor',
      'The Earth is thinner there',
    ],
    explain: 'It is called the Ring of Fire. About three quarters of the world’s volcanoes sit on it.',
  },
  {
    id: 'g-monsoon',
    topic: 'geography',
    rating: 1200,
    prompt: 'What causes the monsoon?',
    options: [
      'Land heats faster than sea, and the wind turns round with the seasons',
      'The Earth tilts towards the rain',
      'Ocean currents change direction',
      'The moon pulls the clouds',
    ],
    explain: 'In summer the hot land pulls wet air in off the sea; in winter it blows the other way. It is the wind reversing, not the rain.',
  },
  {
    id: 'g-longest-border',
    topic: 'geography',
    rating: 1000,
    prompt: 'Which two countries share the longest border in the world?',
    options: ['Canada and the United States', 'Russia and China', 'Chile and Argentina', 'India and China'],
    explain: 'Nearly nine thousand kilometres of it, and most of it runs along lines somebody drew on a map.',
  },
  {
    id: 'g-city-below-sea',
    topic: 'geography',
    rating: 1100,
    prompt: 'How does the Netherlands keep the sea out?',
    options: [
      'Dykes and pumps, and it has been at it for centuries',
      'A very deep harbour',
      'The tide never comes in there',
      'The land is slowly rising',
    ],
    explain: 'About a quarter of the country is below sea level. Windmills were the original pumps.',
  },
  {
    id: 'g-great-lakes',
    topic: 'geography',
    rating: 1000,
    prompt: 'What share of the world’s fresh surface water is in the Great Lakes?',
    options: ['About a fifth', 'About a hundredth', 'About half', 'Almost none'],
    explain: 'They were carved out by ice sheets and filled as the ice melted.',
  },
  {
    id: 'g-city-two-continents',
    topic: 'geography',
    rating: 1050,
    prompt: 'Which large city sits on two continents at once?',
    options: ['Istanbul', 'Cairo', 'Athens', 'Moscow'],
    explain: 'The Bosphorus runs through it: one side is Europe, the other is Asia, and there are bridges between.',
  },
  {
    id: 'g-permafrost',
    topic: 'geography',
    rating: 1200,
    prompt: 'What is permafrost?',
    options: [
      'Ground that has stayed frozen for at least two years',
      'Ice that never melts on a mountain',
      'Snow that has turned to rock',
      'A frozen sea',
    ],
    explain: 'Buildings on it are often raised on stilts, because the warmth of a house can thaw the ground it is standing on.',
  },
  {
    id: 'g-rain-shadow',
    topic: 'geography',
    rating: 1250,
    prompt: 'Why is it often dry on one side of a mountain range and wet on the other?',
    options: [
      'Air drops its rain climbing the range and arrives dry on the far side',
      'The sun only reaches one side',
      'Mountains block clouds completely',
      'Wind never crosses mountains',
    ],
    explain: 'It is called a rain shadow. It is why one side of a range can be forest and the other desert.',
  },
  {
    id: 'g-tide',
    topic: 'geography',
    rating: 1100,
    prompt: 'What makes the tides?',
    options: [
      'Mostly the moon pulling on the ocean',
      'The wind pushing water about',
      'Rivers filling the sea',
      'The Earth wobbling',
    ],
    explain: 'The sun helps. When the two line up you get the biggest tides of the month.',
  },
  {
    id: 'g-map-mercator',
    topic: 'geography',
    rating: 1200,
    prompt: 'Why does Greenland look as big as Africa on many maps?',
    options: [
      'Flattening a globe stretches whatever is near the poles',
      'Greenland really is that big',
      'Maps are drawn from photographs',
      'Africa is usually drawn smaller on purpose',
    ],
    explain: 'Africa is about fourteen times the size. Any flat map has to lie about something: shape, size or distance.',
  },
  {
    id: 'g-lake-baikal',
    topic: 'geography',
    rating: 1150,
    prompt: 'What is remarkable about Lake Baikal in Siberia?',
    options: [
      'It holds a fifth of the world’s unfrozen fresh water',
      'It is the largest lake by area',
      'It never freezes',
      'It has no fish',
    ],
    explain: 'It is over a mile deep in places — a crack in the Earth’s crust that filled up.',
  },
  {
    id: 'g-canal-panama',
    topic: 'geography',
    rating: 1050,
    prompt: 'Why does the Panama Canal need locks?',
    options: [
      'The middle of the crossing is higher than both oceans',
      'The two oceans are different temperatures',
      'To slow the ships down',
      'To keep the sharks out',
    ],
    explain: 'Ships are lifted about 26 metres up to a lake, carried across it, and let down the other side.',
  },
  {
    id: 'g-desert-cold',
    topic: 'geography',
    rating: 1000,
    prompt: 'Why do hot deserts get so cold at night?',
    options: [
      'Dry air holds no heat once the sun goes down',
      'The sand freezes',
      'Wind blows in from the sea',
      'They are usually high up',
    ],
    explain: 'Water vapour is what keeps a night mild. With none in the air, the day’s heat leaves as soon as the sun does.',
  },
  {
    id: 'g-country-most-islands',
    topic: 'geography',
    rating: 1100,
    prompt: 'Which country is made of the most islands?',
    options: ['Sweden', 'Indonesia', 'Japan', 'The Philippines'],
    explain: 'Around 270,000 of them, though most are bare rock. Indonesia has more people spread over its 17,000.',
  },
  {
    id: 'g-river-longest',
    topic: 'geography',
    rating: 950,
    prompt: 'Which carries more water — the Nile or the Amazon?',
    options: ['The Amazon, by a very long way', 'The Nile', 'They are about equal', 'It changes each year'],
    explain: 'The Amazon carries more than the next seven biggest rivers put together. The Nile is longer but much thinner.',
  },
  {
    id: 'g-city-population',
    topic: 'geography',
    rating: 1000,
    prompt: 'Roughly what share of people now live in towns and cities rather than the countryside?',
    options: ['More than half', 'About a quarter', 'About a tenth', 'Nearly everyone'],
    explain: 'It passed half around 2007. For the whole of history before that, most people farmed.',
  },
  {
    id: 'g-glacier',
    topic: 'geography',
    rating: 1150,
    prompt: 'How does a glacier carve a valley?',
    options: [
      'It grinds along, dragging rock with it, and leaves a U-shaped trough',
      'It melts the rock',
      'It cracks stone with cold',
      'It floats the rock away',
    ],
    explain: 'A river cuts a V. A glacier is wide and heavy and scrapes out a U — which is how you can tell which one was there.',
  },
  {
    id: 'g-salt-flat',
    topic: 'geography',
    rating: 1200,
    prompt: 'How did the great salt flats of Bolivia form?',
    options: [
      'A lake with no outlet dried up and left its salt behind',
      'Sea water was trapped by mountains rising',
      'Volcanoes erupted salt',
      'Glaciers left it there',
    ],
    explain: 'Ten thousand square kilometres of it, so flat that satellites use it to check their instruments.',
  },
  {
    id: 'g-fjord',
    topic: 'geography',
    rating: 1150,
    prompt: 'What is a fjord?',
    options: [
      'A glacier-cut valley that the sea has flooded',
      'A river mouth full of sand',
      'A bay made by a volcano',
      'A lake beside the sea',
    ],
    explain: 'They are deep and steep-sided because the ice cut below what is now sea level.',
  },
  {
    id: 'g-gulf-stream',
    topic: 'geography',
    rating: 1250,
    prompt: 'Why is Britain milder than Canada, which is at the same latitude?',
    options: [
      'A warm ocean current carries heat up from the tropics',
      'Britain is further south than it looks',
      'It is closer to the sun in winter',
      'The sea around it is shallow',
    ],
    explain: 'The Gulf Stream. Without it, London winters would be more like Labrador’s.',
  },
]
