/**
 * History.
 *
 * Kingdoms and empires, and then the wars that ended most of them. Weighted
 * towards the parts that are stories rather than dates: a question about when
 * something happened is a question about whether you memorised it, and a
 * question about why it happened is a question about whether you understood
 * it. Several deliberately circle the same few civilisations from different
 * angles — the second time the Indus Valley comes round it is not a new fact,
 * it is a fact you already have being asked to do something with.
 */
import type { Ask } from '../types'

export const HISTORY: readonly Ask[] = [
  // --- the ancient world ---------------------------------------------------
  {
    id: 'h-pyramids',
    topic: 'history',
    rating: 700,
    prompt: 'The Great Pyramid at Giza was built as a tomb for a king of which country?',
    options: ['Egypt', 'Greece', 'China', 'Peru'],
    explain: 'It was built about 4,500 years ago and stayed the tallest building on Earth for nearly 4,000 years.',
  },
  {
    id: 'h-indus-plumbing',
    topic: 'history',
    rating: 900,
    prompt: 'The cities of the Indus Valley had something most cities would not have again for thousands of years. What?',
    options: ['Drains and covered sewers', 'Electric lights', 'Printed newspapers', 'Glass windows'],
    explain: 'Mohenjo-daro had brick drains under its streets and baths in ordinary houses, around 2500 BCE.',
  },
  {
    id: 'h-writing',
    topic: 'history',
    rating: 850,
    prompt: 'What were the very first written records mostly about?',
    options: ['Counting goods and grain', 'Poems', 'Laws', 'Songs'],
    explain: 'Writing began as accounting. People invented it to keep track of who owed what, and stories came later.',
  },
  {
    id: 'h-mummy',
    topic: 'history',
    rating: 750,
    prompt: 'Why did the ancient Egyptians make mummies?',
    options: [
      'They believed the body was needed in the afterlife',
      'To stop diseases spreading',
      'To make them lighter to carry',
      'Because the law said so',
    ],
    explain: 'They dried the body with salt and wrapped it in linen so its owner would still have it after death.',
  },
  {
    id: 'h-zero',
    topic: 'history',
    rating: 1000,
    prompt: 'Zero as a number you can calculate with was first written down in which part of the world?',
    options: ['India', 'Rome', 'Egypt', 'Britain'],
    explain: 'Indian mathematicians used zero as a real number by the 600s. Roman numerals have no zero at all — try writing 101 in them.',
  },
  {
    id: 'h-great-wall',
    topic: 'history',
    rating: 800,
    prompt: 'The Great Wall of China was mainly built to do what?',
    options: ['Keep armies out', 'Hold back a river', 'Mark a road', 'Carry water'],
    explain: 'It is not one wall but many, built and rebuilt over 2,000 years by different rulers.',
  },

  // --- how people worked things out ---------------------------------------
  {
    id: 'h-eratosthenes',
    topic: 'history',
    rating: 1250,
    prompt: 'Over 2,000 years ago a Greek librarian measured the size of the whole Earth using what?',
    options: ['Shadows and a long walk', 'A telescope', 'A ship', 'A very long rope'],
    explain: 'Eratosthenes compared shadows in two cities at noon and got within a few per cent of the right answer.',
  },
  {
    id: 'h-printing',
    topic: 'history',
    rating: 950,
    prompt: 'What did the printing press change most?',
    options: [
      'How many people could own a book',
      'How fast ships could sail',
      'How tall buildings could be',
      'How far letters could travel',
    ],
    explain: 'Before it, a book was copied by hand and cost as much as a house. After it, ideas spread faster than kings could stop them.',
  },
  {
    id: 'h-compass',
    topic: 'history',
    rating: 900,
    prompt: 'The magnetic compass was first used for navigation by sailors from where?',
    options: ['China', 'Portugal', 'Egypt', 'Norway'],
    explain: 'Chinese sailors were using it by about 1100, a century or so before it reached Europe.',
  },
  {
    id: 'h-vaccine',
    topic: 'history',
    rating: 1150,
    prompt: 'Smallpox is the only human disease ever wiped out completely. What did it?',
    options: ['Vaccination', 'Clean water', 'Antibiotics', 'Warmer houses'],
    explain: 'The last natural case was in 1977. It is the only time humans have removed a disease from the world entirely.',
  },
  {
    id: 'h-longitude',
    topic: 'history',
    rating: 1300,
    prompt: 'For centuries sailors could not tell how far east or west they were. What finally solved it?',
    options: ['A clock accurate at sea', 'A better telescope', 'A bigger sail', 'A new kind of map'],
    explain: 'John Harrison spent decades building a clock that kept time on a rolling ship. Knowing the time at home tells you your longitude.',
  },

  // --- people ---------------------------------------------------------------
  {
    id: 'h-ashoka',
    topic: 'history',
    rating: 1200,
    prompt: 'The emperor Ashoka is remembered for doing something unusual after winning a war. What?',
    options: [
      'He gave up war entirely',
      'He burned his own capital',
      'He gave the land back',
      'He crowned his enemy',
    ],
    explain: 'Sickened by the dead at Kalinga, he turned to Buddhism and had his new rules carved on pillars across India. Some still stand.',
  },
  {
    id: 'h-hypatia',
    topic: 'history',
    rating: 1250,
    prompt: 'Hypatia of Alexandria was famous as which of these?',
    options: ['A mathematician and astronomer', 'A queen', 'A general', 'A ship builder'],
    explain: 'She taught mathematics and astronomy in Alexandria around 400 CE, when very few women were allowed to teach anything.',
  },
  {
    id: 'h-mansa-musa',
    topic: 'history',
    rating: 1150,
    prompt: 'Mansa Musa of Mali is often called the richest person who ever lived. What was Mali rich in?',
    options: ['Gold', 'Iron', 'Silk', 'Coal'],
    explain: 'On his journey to Mecca in 1324 he gave away so much gold that its price stayed low in Egypt for years.',
  },
  {
    id: 'h-zheng-he',
    topic: 'history',
    rating: 1200,
    prompt: "Zheng He's treasure fleet sailed from China in the 1400s. How did his ships compare to European ones of the time?",
    options: ['Far bigger', 'Much smaller', 'About the same', 'They had no sails'],
    explain: 'His largest ships may have been four times the length of Columbus’s. China then stopped the voyages and burned the records.',
  },
  {
    id: 'h-rosetta',
    topic: 'history',
    rating: 1100,
    prompt: 'The Rosetta Stone was so useful because it had the same text written how?',
    options: ['In three scripts', 'In very large letters', 'On both sides', 'In gold'],
    explain: 'Greek could already be read, so it became the key that unlocked Egyptian hieroglyphs after 1,400 years of silence.',
  },

  // --- the world moving around ---------------------------------------------
  {
    id: 'h-silk-road',
    topic: 'history',
    rating: 950,
    prompt: 'The Silk Road was not really a road. What was it?',
    options: [
      'A network of trade routes',
      'A single paved highway',
      'A river',
      'A wall',
    ],
    explain: 'Goods, ideas, religions and diseases all travelled it, usually changing hands many times on the way.',
  },
  {
    id: 'h-potato',
    topic: 'history',
    rating: 1050,
    prompt: 'Potatoes, tomatoes and chocolate all came to Europe from where?',
    options: ['The Americas', 'India', 'China', 'Africa'],
    explain: 'None of them existed in Europe before the 1500s. Italian food without tomatoes is only a few hundred years old.',
  },
  {
    id: 'h-nile',
    topic: 'history',
    rating: 800,
    prompt: 'Why did Egyptian farmers welcome the Nile flooding every year?',
    options: [
      'It left rich mud on the fields',
      'It washed the streets',
      'It cooled the air',
      'It brought fish to the doors',
    ],
    explain: 'The flood laid down fertile silt. Egyptians measured it carefully, because too little meant famine and too much meant ruin.',
  },
  {
    id: 'h-olympics',
    topic: 'history',
    rating: 850,
    prompt: 'The ancient Olympic Games were held in honour of which Greek god?',
    options: ['Zeus', 'Apollo', 'Poseidon', 'Athena'],
    explain: 'They ran for about 1,200 years, and wars were paused so that people could travel to them safely.',
  },
  {
    id: 'h-plague-effect',
    topic: 'history',
    rating: 1350,
    prompt: 'After the Black Death killed a huge share of Europe, what happened to the wages of the people left?',
    options: ['They went up', 'They went down', 'They stayed the same', 'They were banned'],
    explain: 'With far fewer workers, labour was suddenly worth more. Some rulers tried to make raising wages illegal, and failed.',
  },
  {
    id: 'h-library',
    topic: 'history',
    rating: 1100,
    prompt: 'The Library of Alexandria tried to do something no library had tried before. What?',
    options: [
      'Collect every book in the world',
      'Lend books to anyone',
      'Print its own books',
      'Keep its books secret',
    ],
    explain: 'Ships arriving in the harbour had their books taken, copied, and the copy given back.',
  },

  // --- nearer the present ---------------------------------------------------
  {
    id: 'h-moon',
    topic: 'history',
    rating: 900,
    prompt: 'In what decade did people first walk on the Moon?',
    options: ['The 1960s', 'The 1940s', 'The 1980s', 'The 2000s'],
    explain: 'July 1969. The computer that guided them had far less memory than the phone this game is running on.',
  },
  {
    id: 'h-flight',
    topic: 'history',
    rating: 1000,
    prompt: 'How long was the first powered aeroplane flight in 1903?',
    options: ['About 12 seconds', 'About an hour', 'About a day', 'About 10 minutes'],
    explain: 'Twelve seconds and 120 feet. Sixty-six years later, people landed on the Moon.',
  },
  {
    id: 'h-penicillin',
    topic: 'history',
    rating: 1150,
    prompt: 'Penicillin, the first antibiotic, was found by accident when a scientist noticed what?',
    options: [
      'Mould killing bacteria in a dish',
      'A dog that never got ill',
      'Bread that would not go stale',
      'A rusty nail that healed',
    ],
    explain: 'Alexander Fleming came back from holiday to a contaminated dish in 1928. He nearly threw it away.',
  },
  {
    id: 'h-computer',
    topic: 'history',
    rating: 1300,
    prompt: 'Who wrote what is often called the first computer program, and for a machine that was never built?',
    options: ['Ada Lovelace', 'Charles Babbage', 'Alan Turing', 'Grace Hopper'],
    explain: 'In the 1840s she worked out how Babbage’s Analytical Engine could compute a sequence of numbers, a century before any computer ran.',
  },
  {
    id: 'h-salt-march',
    topic: 'history',
    rating: 1250,
    prompt: 'In 1930 Gandhi walked 240 miles to the sea to do what?',
    options: ['Make salt', 'Catch a ship', 'Meet a king', 'Visit a temple'],
    explain: 'Making your own salt was illegal under British rule. Breaking that one small law on purpose brought millions into the protest.',
  },
  {
    id: 'h-berlin-wall',
    topic: 'history',
    rating: 1200,
    prompt: 'The Berlin Wall divided a city for 28 years. What happened in 1989?',
    options: ['People opened it and pulled it down', 'It was made taller', 'It was moved', 'It burned'],
    explain: 'A muddled announcement on television sent crowds to the checkpoints, and the guards, with no orders, let them through.',
  },
  {
    id: 'h-internet',
    topic: 'history',
    rating: 1350,
    prompt: 'The internet was first built so that what could keep working?',
    options: [
      'Messages, even if part of the network was destroyed',
      'Television broadcasts',
      'Telephone calls across the sea',
      'Weather forecasts',
    ],
    explain: 'It splits everything into small packets that find their own way, so there is no single wire to cut.',
  },
  {
    id: 'h-lighthouse',
    topic: 'history',
    rating: 1050,
    prompt: 'How did people record what happened before writing was invented?',
    options: [
      'They memorised it and told it aloud',
      'They did not, it was all lost',
      'They drew maps',
      'They carved it in gold',
    ],
    explain: 'Spoken history can last thousands of years. Some Aboriginal Australian stories describe coastlines that the sea covered 7,000 years ago.',
  },
// --- kingdoms and empires ------------------------------------------------
  {
    id: 'h-rome-republic',
    topic: 'history',
    rating: 1050,
    prompt: 'Rome was a republic for centuries before it was an empire. What does a republic mean?',
    options: [
      'The people choose who rules, and there is no king',
      'One family rules forever',
      'Priests make the decisions',
      'The army chooses the ruler',
    ],
    explain: 'Romans had thrown out their last king and hated the word. Augustus took total power but was careful never to call himself one.',
  },
  {
    id: 'h-roman-roads',
    topic: 'history',
    rating: 900,
    prompt: 'Why did the Romans build such straight roads?',
    options: [
      'So armies could move fast between cities',
      'Because curves were harder to build',
      'To make them look impressive',
      'Because the land was flat',
    ],
    explain: 'A straight road is the shortest one. Some still lie under modern roads across Europe, 2,000 years later.',
  },
  {
    id: 'h-maurya',
    topic: 'history',
    rating: 1150,
    prompt: 'Emperor Ashoka ruled most of India, then changed course completely after one war. What did he do?',
    options: [
      'Gave up conquest and spread Buddhism',
      'Built a wall around his empire',
      'Moved his capital to the sea',
      'Divided the empire between his sons',
    ],
    explain: 'The war in Kalinga horrified him. He had his new principles carved onto pillars of stone, and some are still standing.',
  },
  {
    id: 'h-gupta-zero',
    topic: 'history',
    rating: 1200,
    prompt: 'Which idea, worked out by mathematicians in ancient India, changed arithmetic everywhere it reached?',
    options: [
      'Zero as a number you can calculate with',
      'The multiplication sign',
      'Counting in tens',
      'The equals sign',
    ],
    explain: 'Brahmagupta wrote rules for calculating with zero and negative numbers in 628 CE. The idea travelled through the Arab world into Europe.',
  },
  {
    id: 'h-mansa-musa-gold',
    topic: 'history',
    rating: 1100,
    prompt: 'Mansa Musa of Mali took so much gold on one journey that he caused a problem. What was it?',
    options: [
      'He gave away so much that gold lost its value for years',
      'He ran out before getting home',
      'It was all stolen on the way',
      'His camels could not carry it',
    ],
    explain: 'He spent and gave away gold across Egypt in 1324, and the price there stayed down for about a decade.',
  },
  {
    id: 'h-timbuktu',
    topic: 'history',
    rating: 1150,
    prompt: 'What was Timbuktu best known for in the 1500s?',
    options: ['Its libraries and universities', 'Its harbour', 'Its iron mines', 'Its glassmakers'],
    explain: 'A centre of learning on the edge of the Sahara, with thousands of manuscripts. Many survive today.',
  },
  {
    id: 'h-mongol-post',
    topic: 'history',
    rating: 1250,
    prompt: 'The Mongol empire ran a relay of riders and stations right across Asia. What was it for?',
    options: [
      'Carrying messages across the empire in days',
      'Moving the army',
      'Collecting taxes',
      'Trading horses',
    ],
    explain: 'The Yam. Riders swapped to fresh horses at each station, so a message crossed thousands of miles at a gallop.',
  },
  {
    id: 'h-china-exam',
    topic: 'history',
    rating: 1300,
    prompt: 'Imperial China chose many of its officials by written examination. Why was that unusual?',
    options: [
      'Almost everywhere else, the job went to whoever was born to it',
      'Because the exams were easy',
      'Because anyone could sit them',
      'Because it was done in secret',
    ],
    explain: 'The exams ran for over a thousand years. In principle a farmer’s son who studied hard could end up governing a province.',
  },
  {
    id: 'h-inca-roads',
    topic: 'history',
    rating: 1200,
    prompt: 'The Inca ran an empire of millions across the Andes without one thing most empires had. What?',
    options: ['Writing', 'Roads', 'An army', 'Taxes'],
    explain:
      'They kept records on khipu — knotted cords. Thousands of miles of road, bridges over gorges, and no alphabet anywhere in it.',
  },
  {
    id: 'h-aztec-city',
    topic: 'history',
    rating: 1100,
    prompt: 'The Aztec capital Tenochtitlan was built somewhere unusual. Where?',
    options: [
      'On islands in the middle of a lake',
      'On top of a volcano',
      'Inside a canyon',
      'On open desert',
    ],
    explain: 'It had causeways, canals and floating gardens, and was bigger than most European cities of its day. Mexico City sits on it now.',
  },
  {
    id: 'h-ottoman',
    topic: 'history',
    rating: 1250,
    prompt: 'In 1453 the Ottomans took Constantinople, ending an empire over a thousand years old. Which one?',
    options: ['The Byzantine empire', 'The Roman republic', 'The Persian empire', 'The Mongol empire'],
    explain: 'Byzantium was the eastern half of the Roman empire, and it outlived the western half by nearly a thousand years.',
  },
  {
    id: 'h-shogun',
    topic: 'history',
    rating: 1050,
    prompt: 'For over 200 years Japan under the shoguns did something very deliberate. What?',
    options: [
      'Almost completely closed itself to the outside world',
      'Conquered its neighbours',
      'Moved its capital every year',
      'Abolished its army',
    ],
    explain: 'Sakoku. Foreign trade ran through a single controlled port, and leaving the country could cost you your life.',
  },
  {
    id: 'h-vikings-america',
    topic: 'history',
    rating: 950,
    prompt: 'Vikings reached North America around 1000 CE. How do we know?',
    options: [
      'A Norse settlement was dug up in Newfoundland',
      'A map was found in Iceland',
      'Their coins turned up in Mexico',
      'A ship was found in the ice',
    ],
    explain: 'L’Anse aux Meadows, excavated in the 1960s — about 500 years before Columbus sailed.',
  },
  {
    id: 'h-silk-road-ideas',
    topic: 'history',
    rating: 1000,
    prompt: 'Apart from goods, what else travelled the Silk Road?',
    options: ['Ideas, religions and diseases', 'Only silk', 'Only gold', 'Nothing else'],
    explain: 'Buddhism reached China along it, paper travelled west along it, and so did the plague.',
  },

  // --- the world wars ------------------------------------------------------
  {
    id: 'h-ww1-spread',
    topic: 'history',
    rating: 1100,
    prompt: 'One assassination in 1914 pulled most of Europe into war within weeks. Why did it spread so fast?',
    options: [
      'Countries were tied together by promises to defend each other',
      'They all wanted the same city',
      'One country invaded them all at once',
      'There was a shortage of food',
    ],
    explain: 'A web of alliances meant one declaration pulled in the next, and the next. Four empires did not survive it.',
  },
  {
    id: 'h-ww1-trenches',
    topic: 'history',
    rating: 1000,
    prompt: 'Why did soldiers on the Western Front end up living in trenches for years?',
    options: [
      'Machine guns made crossing open ground almost impossible',
      'The ground was too wet to walk on',
      'They were waiting for ships',
      'It was a rule of war at the time',
    ],
    explain: 'Defending had become far easier than attacking, so both sides dug in and the line barely moved for years.',
  },
  {
    id: 'h-ww1-end',
    topic: 'history',
    rating: 950,
    prompt: 'The First World War ended at the 11th hour of the 11th day of the 11th month of which year?',
    options: ['1918', '1916', '1920', '1914'],
    explain: 'The armistice of 11 November 1918. It is still marked at that hour in many countries.',
  },
  {
    id: 'h-ww2-start',
    topic: 'history',
    rating: 1000,
    prompt: 'Which invasion in 1939 started the Second World War in Europe?',
    options: ['Germany invading Poland', 'Germany invading France', 'Italy invading Greece', 'Japan invading China'],
    explain: 'Britain and France had promised to defend Poland, and declared war two days later.',
  },
  {
    id: 'h-ww2-codes',
    topic: 'history',
    rating: 1250,
    prompt: 'At Bletchley Park in Britain, thousands of people worked in secret on what?',
    options: [
      'Breaking enemy codes with early computing machines',
      'Building aircraft',
      'Drawing maps',
      'Training pilots',
    ],
    explain:
      'Breaking the Enigma cipher is thought to have shortened the war by years. The work stayed secret for decades afterwards.',
  },
  {
    id: 'h-ww2-world',
    topic: 'history',
    rating: 1150,
    prompt: 'Why is the Second World War called a world war rather than a European one?',
    options: [
      'It was fought across Asia, Africa and the Pacific too',
      'Every country on Earth joined in',
      'It was reported worldwide',
      'It was agreed at a world meeting',
    ],
    explain: 'Major fighting ran from the Pacific islands to North Africa to the edge of Moscow, and troops came from six continents.',
  },
  {
    id: 'h-un-founded',
    topic: 'history',
    rating: 1100,
    prompt: 'The United Nations was set up in 1945. What was the idea behind it?',
    options: [
      'Somewhere for countries to argue instead of fight',
      'A world army',
      'A single world government',
      'A trading company',
    ],
    explain: 'An earlier attempt, the League of Nations, had failed to stop the Second World War. The UN was the second try.',
  },
  {
    id: 'h-empires-end',
    topic: 'history',
    rating: 1200,
    prompt: 'In the 30 years after 1945, something happened to most of the world’s empires. What?',
    options: [
      'They broke up as colonies became independent countries',
      'They grew larger',
      'They joined together',
      'They moved their capitals',
    ],
    explain: 'Dozens of new countries appeared, starting with India and Pakistan in 1947. It redrew the map of Africa and Asia.',
  },
  {
    id: 'h-cold-war',
    topic: 'history',
    rating: 1300,
    prompt: 'Why was the Cold War called cold?',
    options: [
      'The two sides never fought each other directly',
      'It was fought in the Arctic',
      'It happened in winter',
      'Nobody was hurt',
    ],
    explain: 'The United States and the Soviet Union armed rivals and fought through other wars, but never each other head on.',
  },
  {
    id: 'h-moon-landing',
    topic: 'history',
    rating: 900,
    prompt: 'People first walked on the Moon in which year?',
    options: ['1969', '1959', '1975', '1981'],
    explain: 'Apollo 11, July 1969. The computer that guided it had less memory than a modern doorbell.',
  },
  // --- the second batch, written once the bank had to last ------------------
  {
    id: 'h-printing-china',
    topic: 'history',
    rating: 1150,
    prompt: 'Printing with movable type was invented in Europe in the 1400s. Where had it been done first?',
    options: ['China, about four hundred years earlier', 'Egypt', 'Greece', 'Persia'],
    explain: 'Bi Sheng made type out of baked clay around 1040. Chinese has thousands of characters, so it never saved as much work there as it did with an alphabet.',
  },
  {
    id: 'h-library-alexandria',
    topic: 'history',
    rating: 1100,
    prompt: 'What was the Library of Alexandria trying to do?',
    options: [
      'Collect a copy of every book in the world',
      'Teach reading to everybody',
      'Store the king’s treasure',
      'Keep records of taxes',
    ],
    explain: 'Ships docking at Alexandria had their books confiscated, copied, and the copy handed back.',
  },
  {
    id: 'h-black-death',
    topic: 'history',
    rating: 1200,
    prompt: 'What did the Black Death do to the wages of the people who survived it?',
    options: [
      'Pushed them up sharply, because workers were suddenly scarce',
      'Pushed them down',
      'Left them the same',
      'Ended payment in money altogether',
    ],
    explain: 'A third of Europe died. The survivors could suddenly bargain, and laws were passed trying to stop them.',
  },
  {
    id: 'h-vikings-navigation',
    topic: 'history',
    rating: 1250,
    prompt: 'How did Viking sailors hold a course out of sight of land?',
    options: [
      'By the sun and stars, bird flight, and the colour of the water',
      'With magnetic compasses',
      'By following the coast at all times',
      'With maps drawn from the air',
    ],
    explain: 'They also watched for whales and cloud shapes that form over land you cannot yet see.',
  },
  {
    id: 'h-spices',
    topic: 'history',
    rating: 1200,
    prompt: 'Why did Europeans sail round the world looking for spices?',
    options: [
      'They were enormously valuable and the land routes were controlled by others',
      'They were the only food that kept',
      'They were used as medicine only',
      'They were needed to make gunpowder',
    ],
    explain: 'Pepper was traded by weight against silver. Columbus was looking for a shortcut to that trade when he ran into the Americas.',
  },
  {
    id: 'h-roman-concrete',
    topic: 'history',
    rating: 1250,
    prompt: 'Why is Roman concrete still standing after two thousand years?',
    options: [
      'Volcanic ash in the mix lets it heal its own cracks',
      'It was mixed with iron',
      'It was never used underwater',
      'It is much thicker than modern concrete',
    ],
    explain: 'Sea water reacting with the ash grows new crystals in the cracks. Modern concrete mostly just cracks.',
  },
  {
    id: 'h-samurai-end',
    topic: 'history',
    rating: 1200,
    prompt: 'What happened to Japan’s samurai in the 1870s?',
    options: [
      'Their class was abolished as Japan modernised',
      'They took over the government',
      'They were all killed in a war',
      'They became sailors',
    ],
    explain: 'Within a generation Japan went from swords to steamships and railways, on purpose and at speed.',
  },
  {
    id: 'h-maya-writing',
    topic: 'history',
    rating: 1250,
    prompt: 'What did the Maya do that no other people in the Americas did?',
    options: [
      'Wrote a full language down',
      'Built with stone',
      'Farmed maize',
      'Traded across long distances',
    ],
    explain: 'Their script records dates, kings and wars. Most of the books were burned; the carvings survived.',
  },
  {
    id: 'h-longbow',
    topic: 'history',
    rating: 1150,
    prompt: 'Why were English longbowmen so hard to replace?',
    options: [
      'It took years of practice, and it deformed the archer’s bones',
      'The bows were rare',
      'Only nobles were allowed to shoot',
      'The arrows were expensive',
    ],
    explain: 'Skeletons from the Mary Rose have twisted spines and thickened arms from a lifetime of drawing.',
  },
  {
    id: 'h-suez',
    topic: 'history',
    rating: 1100,
    prompt: 'What did the Suez Canal change when it opened in 1869?',
    options: [
      'Ships no longer had to sail all the way round Africa',
      'Egypt gained a new river',
      'The Mediterranean became tidal',
      'Sailing ships became faster than steam',
    ],
    explain: 'It cut roughly six thousand kilometres off the trip from Europe to India.',
  },
  {
    id: 'h-olympics-gap',
    topic: 'history',
    rating: 1050,
    prompt: 'How long was the gap between the ancient Olympics and the modern ones?',
    options: ['About 1,500 years', 'About 200 years', 'About 500 years', 'There was no gap'],
    explain: 'The ancient games ran for over a thousand years and were stopped around 393 CE. The modern ones began in 1896.',
  },
  {
    id: 'h-coffee-houses',
    topic: 'history',
    rating: 1250,
    prompt: 'What grew out of London’s coffee houses in the 1600s?',
    options: [
      'Newspapers, insurance and the stock exchange',
      'The first schools',
      'The postal service',
      'Parliament',
    ],
    explain: 'Lloyd’s of London began as a coffee house where shipowners met. People called them penny universities.',
  },
  {
    id: 'h-hieroglyph-numbers',
    topic: 'history',
    rating: 1100,
    prompt: 'Why is zero a surprisingly recent idea in Europe?',
    options: [
      'Roman numerals had no need of it, and it arrived from India via the Arab world',
      'Nobody had thought of counting',
      'It was banned by the church everywhere',
      'It was invented by Newton',
    ],
    explain: 'Try writing 1,005 in Roman numerals and you can see why a symbol for nothing is worth having.',
  },
  {
    id: 'h-canals',
    topic: 'history',
    rating: 1150,
    prompt: 'Before railways, what was the cheapest way to move something heavy?',
    options: ['By boat, on a canal or river', 'By cart', 'By packhorse', 'On foot'],
    explain: 'One horse can pull maybe two tonnes on a road and fifty on water. Britain dug thousands of miles of canal before the trains came.',
  },
  {
    id: 'h-terracotta',
    topic: 'history',
    rating: 1100,
    prompt: 'What did farmers digging a well in China find in 1974?',
    options: [
      'An army of eight thousand life-size clay soldiers',
      'A buried city',
      'The oldest book in the world',
      'A gold mine',
    ],
    explain: 'They guard the tomb of the first emperor, and no two faces are the same.',
  },
  {
    id: 'h-tea-clippers',
    topic: 'history',
    rating: 1200,
    prompt: 'Why did tea clippers race each other home from China?',
    options: [
      'The first cargo of the new season sold for far more',
      'It was a sport',
      'The tea went bad quickly',
      'The crews were paid by the day',
    ],
    explain: 'Crowds followed the race in the papers. Steamships and the Suez Canal ended it within a few years.',
  },
  {
    id: 'h-morse',
    topic: 'history',
    rating: 1150,
    prompt: 'What changed when the telegraph arrived?',
    options: [
      'A message could outrun the person carrying it, for the first time ever',
      'Letters became cheaper',
      'Newspapers were invented',
      'Ships stopped carrying mail',
    ],
    explain: 'Before it, news travelled at the speed of a horse or a ship. After it, news was instant and the world got smaller.',
  },
  {
    id: 'h-womens-vote',
    topic: 'history',
    rating: 1100,
    prompt: 'Which country was first to let women vote in national elections?',
    options: ['New Zealand, in 1893', 'Britain', 'The United States', 'France'],
    explain: 'Britain followed partly in 1918, the United States in 1920, France not until 1944.',
  },
  {
    id: 'h-pyramid-workers',
    topic: 'history',
    rating: 1200,
    prompt: 'Who built the Egyptian pyramids?',
    options: [
      'Paid Egyptian workers, housed and fed in villages nearby',
      'Foreign slaves',
      'Priests',
      'Nobody knows at all',
    ],
    explain: 'Their village has been dug up: bakeries, breweries, doctors’ records of mended bones. They were organised into teams with names.',
  },
  {
    id: 'h-silk-secret',
    topic: 'history',
    rating: 1250,
    prompt: 'How did China keep silk-making secret for so long?',
    options: [
      'Telling anyone outside was punishable by death',
      'The worms could not survive elsewhere',
      'It needed a plant only found there',
      'Nobody else wanted silk',
    ],
    explain: 'It held for about two thousand years. The story goes that monks smuggled silkworm eggs out inside hollow canes.',
  },
  {
    id: 'h-clock-sea',
    topic: 'history',
    rating: 1300,
    prompt: 'Why did sailors need an accurate clock to find their way?',
    options: [
      'Knowing the time back home tells you how far east or west you are',
      'To time the tides',
      'To keep the crew on shift',
      'To measure how fast the ship was going',
    ],
    explain: 'Latitude you can read off the sun. Longitude needed a clock that kept time on a rolling ship, and it took John Harrison forty years.',
  },
  {
    id: 'h-castle-stairs',
    topic: 'history',
    rating: 1150,
    prompt: 'Why do castle spiral staircases usually turn clockwise going up?',
    options: [
      'It gave the defender above room to swing a sword and cramped the attacker',
      'It was easier to build',
      'It matched the direction of the sun',
      'It used less stone',
    ],
    explain: 'Assuming both were right-handed. A few castles belonging to left-handed families turn the other way.',
  },
  {
    id: 'h-plague-doctor',
    topic: 'history',
    rating: 1200,
    prompt: 'Why did plague doctors wear those long beaked masks?',
    options: [
      'They believed bad smells carried disease, and packed the beak with herbs',
      'To frighten the illness away',
      'To filter out germs, which they had discovered',
      'It was simply a uniform',
    ],
    explain: 'They were wrong about the smells but the mask and gown did keep fleas off, which was the actual carrier.',
  },
]
