/**
 * Anything else.
 *
 * Science, language, the body, animals, how ordinary things work. The rule for
 * getting into this list is that the answer should be interesting *after* you
 * know it — a question whose answer is just a fact you either had or did not
 * have is a worse question than one whose answer explains something you had
 * already noticed and never asked about.
 */
import type { Ask } from '../types'

export const TRIVIA: readonly Ask[] = [
  {
    id: 't-sky-blue',
    topic: 'trivia',
    rating: 1000,
    prompt: 'Why is the sky blue?',
    options: [
      'Air scatters blue light more than red',
      'It reflects the sea',
      'The sun gives off blue light',
      'The air itself is blue',
    ],
    explain: 'Short blue waves bounce off air molecules far more than long red ones, so blue arrives from all over the sky.',
  },
  {
    id: 't-sunset-red',
    topic: 'trivia',
    rating: 1150,
    prompt: 'If air scatters blue light, why are sunsets red?',
    options: [
      'The light travels through more air, and the blue is scattered away',
      'The sun cools down in the evening',
      'Dust turns it red',
      'The sun is further away',
    ],
    explain: 'At sunset the light comes in at a low angle through much more air. The blue is scattered out before it reaches you.',
  },
  {
    id: 't-moon-same-face',
    topic: 'trivia',
    rating: 1200,
    prompt: 'Why do we always see the same side of the Moon?',
    options: [
      'It turns once for every trip round the Earth',
      'It does not turn at all',
      'The other side is always dark',
      'It is too far to see the rest',
    ],
    explain: 'Its spin and its orbit take exactly the same time, so the same face keeps pointing at us. The far side is not dark, just hidden.',
  },
  {
    id: 't-lightning-thunder',
    topic: 'trivia',
    rating: 900,
    prompt: 'Why do you see lightning before you hear the thunder?',
    options: [
      'Light travels much faster than sound',
      'The thunder starts later',
      'Sound goes round the clouds',
      'Your eyes work faster than your ears',
    ],
    explain: 'Light is almost instant; sound takes about three seconds per kilometre. Count the gap and you know how far away it was.',
  },
  {
    id: 't-boiling',
    topic: 'trivia',
    rating: 1100,
    prompt: 'What is actually happening when water boils?',
    options: [
      'It is turning into gas fast enough to make bubbles inside itself',
      'The water is getting hotter and hotter',
      'Air trapped in it is escaping',
      'It is splitting into hydrogen and oxygen',
    ],
    explain: 'Once it boils, extra heat goes into turning water to steam rather than raising the temperature. It stays at 100 °C.',
  },
  {
    id: 't-ice-floats',
    topic: 'trivia',
    rating: 1050,
    prompt: 'Why does ice float when almost every other solid sinks in its own liquid?',
    options: [
      'Water molecules lock into a pattern with gaps in it',
      'Ice has air trapped inside',
      'Ice is colder',
      'Ice is a different substance',
    ],
    explain: 'Freezing pushes water molecules into an open lattice, so ice takes up more room than the water it came from. Ponds freeze from the top down because of it.',
  },
  {
    id: 't-heart',
    topic: 'trivia',
    rating: 950,
    prompt: 'How many chambers does a human heart have?',
    options: ['Four', 'Two', 'Three', 'Six'],
    explain: 'Two receive blood, two pump it out. One side sends blood to the lungs, the other to the rest of you.',
  },
  {
    id: 't-bones-baby',
    topic: 'trivia',
    rating: 1000,
    prompt: 'Who has more bones: a baby or an adult?',
    options: ['A baby', 'An adult', 'They have the same', 'It depends on height'],
    explain: 'Babies have around 300. Many fuse together as you grow, leaving an adult with 206.',
  },
  {
    id: 't-blood-blue',
    topic: 'trivia',
    rating: 1100,
    prompt: 'Is the blood in your veins blue?',
    options: [
      'No, it is dark red — the veins only look blue through skin',
      'Yes, until it meets air',
      'Yes, in the veins only',
      'It is blue in children and red in adults',
    ],
    explain: 'It is dark red all the way round. Skin scatters light in a way that makes the veins underneath look blue.',
  },
  {
    id: 't-octopus',
    topic: 'trivia',
    rating: 1050,
    prompt: 'How many hearts does an octopus have?',
    options: ['Three', 'One', 'Two', 'Eight'],
    explain: 'Two push blood through the gills and one sends it round the body. That one stops when the octopus swims, which is why they prefer to crawl.',
  },
  {
    id: 't-honey',
    topic: 'trivia',
    rating: 1150,
    prompt: 'Why does honey almost never go off?',
    options: [
      'It is too dry and too acidic for microbes to live in',
      'Bees add a preservative',
      'It is sealed from air',
      'Sugar cannot rot',
    ],
    explain: 'It pulls water out of any microbe that lands in it. Pots of honey found in Egyptian tombs were still honey.',
  },
  {
    id: 't-tallest-animal',
    topic: 'trivia',
    rating: 800,
    prompt: 'How many neck bones does a giraffe have?',
    options: ['Seven — the same as you', 'Twenty', 'Twelve', 'Thirty'],
    explain: 'Almost every mammal has seven, from a mouse to a whale. A giraffe’s are simply enormous.',
  },
  {
    id: 't-largest-animal',
    topic: 'trivia',
    rating: 850,
    prompt: 'What is the largest animal that has ever lived?',
    options: ['The blue whale', 'The largest dinosaur', 'The African elephant', 'The giant squid'],
    explain: 'Bigger than any dinosaur we have found. Its tongue alone can weigh as much as an elephant.',
  },
  {
    id: 't-speed-light',
    topic: 'trivia',
    rating: 1250,
    prompt: 'Light from the sun takes about how long to reach us?',
    options: ['Eight minutes', 'A second', 'An hour', 'A day'],
    explain: 'So you never see the sun as it is now, only as it was eight minutes ago.',
  },
  {
    id: 't-stars-past',
    topic: 'trivia',
    rating: 1300,
    prompt: 'Why is looking at a distant star the same as looking into the past?',
    options: [
      'Its light took years to get here',
      'Stars are older than us',
      'Space bends time',
      'Telescopes record old light',
    ],
    explain: 'Some stars you can see with the naked eye are so far away that their light set off before anyone alive was born.',
  },
  {
    id: 't-planet-hot',
    topic: 'trivia',
    rating: 1200,
    prompt: 'Which planet is the hottest?',
    options: ['Venus', 'Mercury', 'Mars', 'Jupiter'],
    explain: 'Mercury is nearer the sun, but Venus has a thick blanket of an atmosphere that traps heat and never lets it go.',
  },
  {
    id: 't-gravity-moon',
    topic: 'trivia',
    rating: 1100,
    prompt: 'A hammer and a feather are dropped together on the Moon. What happens?',
    options: [
      'They land at the same moment',
      'The hammer lands first',
      'The feather floats away',
      'Neither of them falls',
    ],
    explain: 'Gravity pulls everything the same. On Earth air slows the feather; on the Moon there is no air. Apollo 15 actually tried it.',
  },
  {
    id: 't-rainbow',
    topic: 'trivia',
    rating: 1050,
    prompt: 'Why can you never reach the end of a rainbow?',
    options: [
      'It is made of light bending in raindrops in front of you',
      'It moves too fast',
      'It is too far away',
      'It is an illusion in your eye',
    ],
    explain: 'A rainbow is not in a place. It depends on where you are standing, so it moves as you do. Two people never see quite the same one.',
  },
  {
    id: 't-echo',
    topic: 'trivia',
    rating: 900,
    prompt: 'What is an echo?',
    options: [
      'Sound bouncing off something and coming back',
      'Sound getting louder',
      'Your ears hearing twice',
      'Sound travelling in a circle',
    ],
    explain: 'You need distance for one: the sound has to take long enough coming back that you hear it as separate.',
  },
  {
    id: 't-mirror',
    topic: 'trivia',
    rating: 1250,
    prompt: 'A mirror swaps your left and right. Why does it not swap your head and feet?',
    options: [
      'It swaps front and back, and you do the rest',
      'Because your eyes are side by side',
      'Because you are taller than you are wide',
      'It does, but you cannot see it',
    ],
    explain: 'It only reverses the direction facing it. You call that left and right because you imagine turning yourself round to match.',
  },
  {
    id: 't-language-most',
    topic: 'trivia',
    rating: 1150,
    prompt: 'Roughly how many languages are spoken in the world today?',
    options: ['About 7,000', 'About 200', 'About 900', 'About 40,000'],
    explain: 'Around half of them are spoken by fewer than 10,000 people, and a language dies roughly every few weeks.',
  },
  {
    id: 't-alphabet',
    topic: 'trivia',
    rating: 1200,
    prompt: 'Where does the word "alphabet" come from?',
    options: [
      'The first two Greek letters, alpha and beta',
      'An old word for writing',
      'The name of its inventor',
      'The Latin for list',
    ],
    explain: 'And alpha and beta came from older Semitic words for ox and house, because the letters started as tiny pictures.',
  },
  {
    id: 't-qwerty',
    topic: 'trivia',
    rating: 1250,
    prompt: 'Why are the letters on a keyboard in such a strange order?',
    options: [
      'It was designed for mechanical typewriters and never changed',
      'It is the fastest possible order',
      'It is alphabetical in another language',
      'It was chosen at random',
    ],
    explain: 'Common pairs were spread out so the metal arms hit the page in turn instead of jamming. The jam went away; the layout stayed.',
  },
  {
    id: 't-paper-fold',
    topic: 'trivia',
    rating: 1300,
    prompt: 'If you could fold a sheet of paper in half 42 times, roughly how thick would it be?',
    options: [
      'Far enough to reach the Moon',
      'About as tall as a house',
      'About a metre',
      'About as tall as a mountain',
    ],
    explain: 'Each fold doubles it. Doubling 42 times from a tenth of a millimetre gets you past 400,000 km.',
  },
  {
    id: 't-glass-liquid',
    topic: 'trivia',
    rating: 1350,
    prompt: 'Old windows are sometimes thicker at the bottom. Why?',
    options: [
      'That is how they were made — glass does not flow',
      'Glass slowly runs downwards',
      'Rain wears the top away',
      'The frames squash them',
    ],
    explain:
      'A popular story says glass is a slow liquid. It is not: old panes were uneven when new, and people sensibly put the thick edge at the bottom.',
  },
  {
    id: 't-bird-dinosaur',
    topic: 'trivia',
    rating: 1100,
    prompt: 'What is the closest living relative of Tyrannosaurus rex?',
    options: ['A chicken', 'A crocodile', 'A lizard', 'A frog'],
    explain: 'Birds are dinosaurs — the branch that made it through. There is a real sense in which dinosaurs never went extinct.',
  },
  {
    id: 't-tree-mass',
    topic: 'trivia',
    rating: 1300,
    prompt: 'Where does most of the material in a tree trunk come from?',
    options: ['The air', 'The soil', 'Water', 'Sunlight'],
    explain: 'Carbon pulled out of the air as carbon dioxide. A tree is built mostly from thin air and light.',
  },
  {
    id: 't-water-cycle',
    topic: 'trivia',
    rating: 1150,
    prompt: 'Is the water you drink today new water?',
    options: [
      'No — almost all of it has been here for billions of years',
      'Yes, it is made fresh by rain',
      'Yes, plants make it',
      'Some is new and some is old',
    ],
    explain: 'It goes round and round: sea, cloud, rain, river, sea. The same water has been through a great many other living things.',
  },
  {
    id: 't-sound-space',
    topic: 'trivia',
    rating: 1000,
    prompt: 'Why is there no sound in space?',
    options: [
      'Sound needs something to travel through, and space is nearly empty',
      'Space is too cold',
      'Sound is pulled away by gravity',
      'There is nothing there to make a noise',
    ],
    explain: 'Sound is a squeeze passing through air or water or rock. With almost no particles, there is nothing to pass it on.',
  },
  {
    id: 't-magnet-earth',
    topic: 'trivia',
    rating: 1200,
    prompt: 'What makes a compass needle point north?',
    options: [
      'The Earth behaves like a giant magnet',
      'The North Pole is made of iron',
      'The stars pull it',
      'The spin of the Earth',
    ],
    explain: 'Molten iron moving deep inside the planet makes the field. It has flipped over many times in the past.',
  },
  {
    id: 't-fingerprints',
    topic: 'trivia',
    rating: 950,
    prompt: 'Do identical twins have identical fingerprints?',
    options: ['No', 'Yes, always', 'Only if they are boys', 'Only at birth'],
    explain: 'They share their DNA, but the ridges form partly by chance in the womb, so even twins differ.',
  },
  {
    id: 't-sleep',
    topic: 'trivia',
    rating: 1100,
    prompt: 'Roughly what fraction of a human life is spent asleep?',
    options: ['About a third', 'About a tenth', 'About half', 'About a fifth'],
    explain: 'Eight hours in twenty-four. Sleep is when the brain files away what it learned during the day, which is why it matters before a test.',
  },
  {
    id: 't-eiffel',
    topic: 'trivia',
    rating: 1250,
    prompt: 'The Eiffel Tower is taller in summer than in winter. Why?',
    options: [
      'Metal expands when it is warm',
      'It is rebuilt each year',
      'The ground swells',
      'It is measured differently',
    ],
    explain: 'Iron grows as it warms. The tower gains something like 15 cm on a hot day.',
  },
  {
    id: 't-zero-invented',
    topic: 'trivia',
    rating: 1300,
    prompt: 'Why was inventing a symbol for zero such a big step?',
    options: [
      'It lets you tell 12 from 102 by where the digits sit',
      'It made counting faster',
      'It gave people a word for nothing',
      'It made multiplication possible',
    ],
    explain: 'Without a mark for an empty column you cannot tell which column anything is in, and the whole place-value system falls apart.',
  },
  {
    id: 't-why-yawn',
    topic: 'trivia',
    rating: 1050,
    prompt: 'What do scientists say about why yawning is catching?',
    options: [
      'They are still not certain',
      'It spreads a germ',
      'It is a sign of hunger',
      'It cools the room',
    ],
    explain: 'It really does spread between people, and even between people and dogs. The reason is still argued about.',
  },
]
