/**
 * The levels.
 *
 * Fifteen rows, because that is how tall the screen is: everything you might
 * jump onto is always in view, and there is no vertical scrolling to hide it.
 *
 * Generated by `scripts/pipes.py` and then proved. The ground is laid first as
 * a route that is known to be crossable — no gap wider than a running jump, no
 * block higher than a jump from the floor beneath it — and the decoration is
 * hung off it afterwards, where it cannot seal anything. `solve.test.ts` then
 * plays each level with the game's own physics and checks the flag can be
 * reached, so a level that cannot be finished fails the build.
 *
 * That check exists here from the start because the dungeon shipped thirteen
 * levels that were every one of them impossible, and the only way anyone found
 * out was by playing one and getting stuck.
 *
 *   ' ' sky        '#' earth       'S' solid block   'B' brick
 *   '?' coin block '!' mushroom    'o' coin          '|' flagpole
 *   '[' ']' pipe lip   '(' ')' pipe shaft
 *   'g' goomba     'k' koopa       '=' the flag's footing
 */
import { readLevel, type Level } from './level'


const LEVEL_1 = [
  '                                                                                                                                                                                              ',
  '                                                                                                                                                                                              ',
  '                                                                                                                                                                                              ',
  '                                                                                                                                                                                              ',
  '                                                                                                                                                                                  |           ',
  '                                                                                                                                                                                  |           ',
  '                                                                                                                                                                                  |           ',
  '                                                                                                                                                                                  |           ',
  '                                                                                                                                                                                  |           ',
  '                            B!B?B      B?B?B     B?!?     B?B?B         B?B     B?B?      SS      B?B?B      B?B?                    B?B?       B?B?B        B?B                  |           ',
  '                                  SS                   []   o o o oSS    o o      o o    SSSS                 o o   [] o o        o o         o o                 o o o o       o | o         ',
  '                   SS            SSSS        []        ()         SSSS                  SSSSSS                      ()                                  SS                        |           ',
  '                  SSSS    g     SSSSSSg      ()   g    ()        SSSSSS               gSSSSSSSS     g               ()  g             g                SSSS                g      =           ',
  '#############################################()########()#####################  ########################   #########()########   #############################################################',
  '#############################################()########()#####################  ########################   #########()########   #############################################################',
]


const LEVEL_2 = [
  '                                                                                                                                                                                              ',
  '                                                                                                                                                                                              ',
  '                                                                                                                                                                                              ',
  '                                                                                                                                                                                              ',
  '                                                                                                                                                                                  |           ',
  '                                                                                                                                                                                  |           ',
  '                                                                                                                                                                                  |           ',
  '                                                                                                                                                                                  |           ',
  '                                                                                                                                                                                  |           ',
  '                                           B?!      B?B?   []                             B?B!B     ?B       SS    B?B?B       !?B?B     B?B             []                       |           ',
  '                    SS                         []          ()              o o         o o o o  SS   o o o  SSSS    o o                                  ()    o o o o            |           ',
  '                   SSSS            SS          ()          ()                                  SSSS        SSSSSS         []                             ()                       |           ',
  '                  SSSSSS       k  SSSS      g  ()          ()           k           g         SSSSSSk     SSSSSSSS   g    ()  g                 g        ()  g            g       =           ',
  '###############################################()##########()#############################################################()#############################()###################################',
  '###############################################()##########()#############################################################()#############################()###################################',
]


const LEVEL_3 = [
  '                                                                                                                                                                                              ',
  '                                                                                                                                                                                              ',
  '                                                                                                                                                                                              ',
  '                                                                                                                                                                                              ',
  '                                                                                                                                                                                  |           ',
  '                                                                                                                                                                                  |           ',
  '                                                                                                                                                                                  |           ',
  '                                                                                                                                                                                  |           ',
  '                                                                                                                                                                                  |           ',
  '                                                B?B!      B?B       B?B       SS    B?B       B?!?B                 B?B?   SS        B?B?B    ?B                                  |           ',
  '                  []  o o        o o o          o o o o         []           SSSS  o o o o o o    []                      SSSS                o o o   SS              o o         |           ',
  '                  ()                                            ()          SSSSSS                ()                     SSSSSS            SS        SSSS                         |           ',
  '                  ()              g           k           g     ()  g      SSSSSSSS g          g  ()     k             gSSSSSSSS        k SSSS     gSSSSSS        k        k      =           ',
  '##################()########    ##########  #########   ########()################################()##########   #############################################################################',
  '##################()########    ##########  #########   ########()################################()##########   #############################################################################',
]


const LEVEL_4 = [
  '                                                                                                                                                                                              ',
  '                                                                                                                                                                                              ',
  '                                                                                                                                                                                              ',
  '                                                                                                                                                                                              ',
  '                                                                                                                                                                                  |           ',
  '                                                                                                                                                                                  |           ',
  '                                                                                                                                                                                  |           ',
  '                                                                                                                                                                                  |           ',
  '                                                                                                                                                                                  |           ',
  '                                                                                        !?B          !?B       B?B?B       B?B?B              SS                                  |           ',
  '                        o o   []    o o o o              SS   o o                []                            o o    []                     SSSS          SS            o o      |           ',
  '                   SS         ()         []             SSSS                     ()                        SS         ()                    SSSSSS        SSSS                    |           ',
  '                  SSSS     g  ()     g   ()   k        SSSSSS    g         g     ()       g        k      SSSS  g     ()   g            k  SSSSSSSS     gSSSSSS      g            =           ',
  '##############################()#########()######################################()##########  #######################()#######    ###########################################################',
  '##############################()#########()######################################()##########  #######################()#######    ###########################################################',
]


const LEVEL_5 = [
  '                                                                                                                                                                                              ',
  '                                                                                                                                                                                              ',
  '                                                                                                                                                                                              ',
  '                                                                                                                                                                                              ',
  '                                                                                                                                                                                  |           ',
  '                                                                                                                                                                                  |           ',
  '                                                                                                                                                                                  |           ',
  '                                                                                                                                                                                  |           ',
  '                                                                                                                                                                                  |           ',
  '                                                                    !?B?                       []        B?!?B        B?B                      B?B?       B?B?                    |           ',
  '                    SS            SS                    o o o oo o          o o                ()      o o          o o o o                   o o  []       o o o o o             |           ',
  '                   SSSS          SSSS                                                          ()             SS                                   ()                             |           ',
  '                  SSSSSS      g SSSSSS      g          k        g        g             g       ()  g        kSSSS      g           g        g      ()   k        k         g      =           ',
  '################################################   ############################################()#########################    ########   ##########()#########################################',
  '################################################   ############################################()#########################    ########   ##########()#########################################',
]

export const LEVELS: readonly Level[] = [
  readLevel('The Waterworks', LEVEL_1),
  readLevel("Papa's Plumbing", LEVEL_2),
  readLevel('The Deep End', LEVEL_3),
  readLevel('Overflow', LEVEL_4),
  readLevel('The Cistern', LEVEL_5),
]

export function levelFor(number: number): Level {
  return LEVELS[Math.min(Math.max(1, number), LEVELS.length) - 1]
}
