"""
Where src/dave/levels.ts comes from.

The levels are drawn here as five screens of twenty columns, because that is
exactly what the player sees at a time and it is the only way anyone can
picture one. `emit.py` joins each set of screens into the hundred-wide rows the
game wants and writes the TypeScript.

Running this file on its own checks the drawings: screen sizes, one trophy and
one door apiece, a floor with no see-through gaps, and a start that is not
inside a wall. It also caps how wide a pit may be on the levels meant to be
crossed on foot. Nine faults in the first draft came out of these checks, and
not one of them was visible by looking.

Whether a level can actually be *finished* is a harder question and lives in
src/dave/solve.ts, which plays each one with the real physics.
"""
# Each screen is 10 rows of exactly 20 characters: one viewport.
# ' ' sky   '#' brick   '^' fire   '~' water   '!' tentacle
# 'T' trophy 'D' door   'J' jetpack 'G' gun
# '1'..'6' gumball, shoe, coin, ring, wand, crown

L = {}

L[1] = dict(start=(2, 8), screens=[
[   "                    ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "         11         ",
    "        ####        ",
    "   1                ",
    "####################"],
[   "                    ",
    "                    ",
    "                    ",
    "                    ",
    "             22     ",
    "            ####    ",
    "                    ",
    "    22              ",
    "   ####             ",
    "########^^^^########"],
[   "                    ",
    "                    ",
    "                    ",
    "      33            ",
    "     #####          ",
    "                    ",
    "                3   ",
    "              ####  ",
    "                    ",
    "####^^^^########^^^^"],
[   "                    ",
    "                    ",
    "         T          ",
    "       ######       ",
    "                    ",
    "   44               ",
    "  #####             ",
    "                    ",
    "               44   ",
    "################^^^^"],
[   "                    ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "        55          ",
    "       #####        ",
    "              D     ",
    "^^##################"],
])

L[2] = dict(start=(2, 8), screens=[
[   "                    ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "          11        ",
    "         #####      ",
    "                    ",
    "   1                ",
    "####################"],
[   "                    ",
    "                    ",
    "         22         ",
    "        #####       ",
    "                    ",
    "   2                ",
    "  ####              ",
    "                    ",
    "                    ",
    "##^^^^####^^^^######"],
[   "                    ",
    "                    ",
    "                    ",
    "             33     ",
    "            #####   ",
    "                    ",
    "      33            ",
    "     #####          ",
    "                    ",
    "####^^^^^^^^########"],
[   "                    ",
    "                    ",
    "    T               ",
    "   #####            ",
    "                    ",
    "              44    ",
    "            #####   ",
    "                    ",
    "                    ",
    "########^^^^########"],
[   "                    ",
    "                    ",
    "                    ",
    "        55          ",
    "       #####        ",
    "                    ",
    "                    ",
    "            6       ",
    "          D         ",
    "^^##################"],
])

L[3] = dict(start=(2, 8), screens=[
[   "                    ",
    "   !     !          ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "        11          ",
    "       #####        ",
    "     1              ",
    "####################"],
[   "                    ",
    "     !       !      ",
    "                    ",
    "                    ",
    "        22          ",
    "       #####        ",
    "                    ",
    "                    ",
    "                    ",
    "####~~~~####~~~~####"],
[   "                    ",
    "         !          ",
    "                    ",
    "     33             ",
    "    #####           ",
    "                    ",
    "            33      ",
    "           #####    ",
    "                    ",
    "##~~~~~~~~~~~~~~####"],
[   "                    ",
    "   !      !         ",
    "        T           ",
    "      ######        ",
    "                    ",
    "   44               ",
    "  #####             ",
    "                    ",
    "                    ",
    "####~~~~####~~~~####"],
[   "                    ",
    "                    ",
    "                    ",
    "         55         ",
    "        #####       ",
    "                    ",
    "                    ",
    "             D      ",
    "                    ",
    "####################"],
])

L[4] = dict(start=(2, 8), screens=[
[   "                    ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "        J           ",
    "       #####        ",
    "     11             ",
    "####################"],
[   "                    ",
    "                    ",
    "        22          ",
    "                    ",
    "      33            ",
    "                    ",
    "    22              ",
    "                    ",
    "                    ",
    "^^^^^^^^^^^^^^^^^^^^"],
[   "      44            ",
    "                    ",
    "            44      ",
    "                    ",
    "   33               ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "^^^^^^^^^^^^^^^^^^^^"],
[   "                    ",
    "         T          ",
    "       ######       ",
    "                    ",
    "                    ",
    "              J     ",
    "            #####   ",
    "                    ",
    "   55               ",
    "########^^^^^^^^####"],
[   "                    ",
    "                    ",
    "                    ",
    "          66        ",
    "         #####      ",
    "                    ",
    "                    ",
    "               D    ",
    "                    ",
    "####################"],
])

L[5] = dict(start=(2, 8), screens=[
[   "                    ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "         G          ",
    "        #####       ",
    "     11             ",
    "####################"],
[   "                    ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "          22        ",
    "         #####      ",
    "                    ",
    "    33              ",
    "####################"],
[   "                    ",
    "                    ",
    "                    ",
    "                    ",
    "         44         ",
    "        #####       ",
    "                    ",
    "    33              ",
    "   #####            ",
    "####^^^^^^^^^^^^####"],
[   "                    ",
    "                    ",
    "         T          ",
    "       ######       ",
    "                    ",
    "      55            ",
    "     #####          ",
    "                    ",
    "                    ",
    "####################"],
[   "                    ",
    "                    ",
    "                    ",
    "                    ",
    "        66          ",
    "       #####        ",
    "                    ",
    "             D      ",
    "                    ",
    "####################"],
])

L[6] = dict(start=(2, 8), screens=[
[   "                    ",
    "    !     !    !    ",
    "                    ",
    "                    ",
    "                    ",
    "         G          ",
    "        #####       ",
    "                    ",
    "     11             ",
    "####################"],
[   "                    ",
    "   !   !   !   !    ",
    "                    ",
    "         22         ",
    "        #####       ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "##^^^^##^^^^##^^^^##"],
[   "                    ",
    "     !       !      ",
    "                    ",
    "                    ",
    "      33     33     ",
    "     ####   ####    ",
    "                    ",
    "                    ",
    "                    ",
    "####~~~~~~~~~~~~####"],
[   "                    ",
    "   !    !     !     ",
    "        T           ",
    "      ######        ",
    "                    ",
    "   44               ",
    "  #####             ",
    "                    ",
    "              55    ",
    "############^^^^####"],
[   "                    ",
    "      !       !     ",
    "                    ",
    "                    ",
    "        66          ",
    "       #####        ",
    "                    ",
    "            D       ",
    "                    ",
    "####################"],
])

L[7] = dict(start=(2, 8), screens=[
[   "                    ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "         11         ",
    "        #####       ",
    "                    ",
    "      11            ",
    "####################"],
[   "                    ",
    "                    ",
    "                    ",
    "          33        ",
    "         #####      ",
    "                    ",
    "     22             ",
    "    #####           ",
    "                    ",
    "####################"],
[   "                    ",
    "         44         ",
    "        #####       ",
    "                    ",
    "      44            ",
    "     #####          ",
    "                    ",
    "    33              ",
    "   #####            ",
    "####^^^^####^^^^####"],
[   "                    ",
    "         T          ",
    "       ######       ",
    "                    ",
    "      55            ",
    "     #####          ",
    "                    ",
    "    55              ",
    "   #####            ",
    "####################"],
[   "                    ",
    "                    ",
    "                    ",
    "         66         ",
    "        #####       ",
    "                    ",
    "                    ",
    "           D        ",
    "                    ",
    "####################"],
])

L[8] = dict(start=(2, 8), screens=[
[   "                    ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "        J           ",
    "       #####        ",
    "                    ",
    "     11    22       ",
    "####################"],
[   "    33              ",
    "                    ",
    "             33     ",
    "                    ",
    "     44             ",
    "                    ",
    "                    ",
    "            44      ",
    "                    ",
    "^^^^^^^^^^^^^^^^^^^^"],
[   "           55       ",
    "                    ",
    "    55              ",
    "                    ",
    "                    ",
    "         66         ",
    "                    ",
    "                    ",
    "                    ",
    "~~~~~~~~~~~~~~~~~~~~"],
[   "                    ",
    "        T           ",
    "      ######        ",
    "                    ",
    "             J      ",
    "           #####    ",
    "                    ",
    "   33               ",
    "  #####             ",
    "####^^^^^^^^^^^^####"],
[   "                    ",
    "                    ",
    "                    ",
    "         66         ",
    "        #####       ",
    "                    ",
    "                    ",
    "              D     ",
    "                    ",
    "####################"],
])

L[9] = dict(start=(2, 8), screens=[
[   "                    ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "         G          ",
    "        #####       ",
    "                    ",
    "      11            ",
    "####################"],
[   "                    ",
    "                    ",
    "                    ",
    "                    ",
    "         22         ",
    "        #####       ",
    "                    ",
    "    33              ",
    "   #####            ",
    "####~~~~~~~~~~~~####"],
[   "                    ",
    "     !      !       ",
    "                    ",
    "                    ",
    "           44       ",
    "          #####     ",
    "                    ",
    "    44              ",
    "   #####            ",
    "##~~~~~~~~~~~~~~~~##"],
[   "                    ",
    "         T          ",
    "       ######       ",
    "                    ",
    "        55          ",
    "       #####        ",
    "                    ",
    "   55               ",
    "  #####             ",
    "####^^^^####^^^^####"],
[   "                    ",
    "                    ",
    "         66         ",
    "        #####       ",
    "                    ",
    "                    ",
    "            D       ",
    "                    ",
    "                    ",
    "####################"],
])

L[10] = dict(start=(2, 8), screens=[
[   "                    ",
    "   !      !     !   ",
    "                    ",
    "                    ",
    "                    ",
    "         G          ",
    "        #####       ",
    "                    ",
    "     11    22       ",
    "####################"],
[   "                    ",
    "    !    !    !     ",
    "                    ",
    "                    ",
    "         33    J    ",
    "        #####  #####",
    "                    ",
    "    33              ",
    "   #####            ",
    "##^^^^##^^^^##^^^^##"],
[   "                    ",
    "                    ",
    "                    ",
    "        66          ",
    "       #####        ",
    "                    ",
    "      44            ",
    "            44      ",
    "                    ",
    "~~~~~~~~~~~~~~~~~~~~"],
[   "                    ",
    "   !     !      !   ",
    "         T          ",
    "       ######       ",
    "                    ",
    "        55          ",
    "       #####        ",
    "                    ",
    "   55               ",
    "####~~~~~~~~####^^^^"],
[   "                    ",
    "      !      !      ",
    "                    ",
    "         66         ",
    "        #####       ",
    "                    ",
    "                    ",
    "           D        ",
    "                    ",
    "####################"],
])


# Levels crossed on foot may not have a hazard run in the floor wider than a
# jump can clear. Dave reaches 5.3 tiles in the air and crossing an N-tile pit
# costs N+1, so two is the widest that leaves any margin worth having -- and
# margin is the point, because a nine year old should not have to frame-count.
#
# Runs wider than that are shrunk from the middle. Four of them were six tiles
# wide where two screens happened to meet, which is invisible while you are
# drawing one screen at a time and fatal once they are joined up.
FOOT_LEVELS = [1, 2, 3, 5, 6, 7, 9]
MAX_PIT = 2

def tame_floor(rows):
    floor = list(rows[9])
    x = 0
    while x < len(floor):
        if floor[x] in '^~':
            run = x
            while run < len(floor) and floor[run] == floor[x]:
                run += 1
            width = run - x
            if width > MAX_PIT:
                keep_from = x + (width - MAX_PIT) // 2
                for i in range(x, run):
                    if not (keep_from <= i < keep_from + MAX_PIT):
                        floor[i] = '#'
            x = run
        else:
            x += 1
    rows[9] = ''.join(floor)
    return rows

for n in FOOT_LEVELS:
    lv = L[n]
    rows = [''.join(sc[r] for sc in lv['screens']) for r in range(10)]
    rows = tame_floor(rows)
    lv['screens'] = [[rows[r][s * 20:(s + 1) * 20] for r in range(10)] for s in range(5)]

# --- validate -------------------------------------------------------------
bad = 0
for n, lv in sorted(L.items()):
    if len(lv['screens']) != 5:
        print(f'level {n}: {len(lv["screens"])} screens, want 5'); bad += 1
    for si, sc in enumerate(lv['screens']):
        if len(sc) != 10:
            print(f'level {n} screen {si}: {len(sc)} rows, want 10'); bad += 1
        for ri, row in enumerate(sc):
            if len(row) != 20:
                print(f'level {n} screen {si} row {ri}: {len(row)} chars, want 20 -> {row!r}'); bad += 1
    rows = [''.join(sc[r] for sc in lv['screens']) for r in range(10)]
    joined = '\n'.join(rows)
    for tile, label in (('T', 'trophy'), ('D', 'door')):
        c = joined.count(tile)
        if c != 1:
            print(f'level {n}: {c} {label}s, want 1'); bad += 1
    floor = rows[9]
    holes = [x for x, t in enumerate(floor) if t not in '#^~']
    if holes:
        print(f'level {n}: {len(holes)} see-through floor columns at {holes[:8]}'); bad += 1
    sx, sy = lv['start']
    if rows[sy][sx] != ' ':
        print(f'level {n}: start is inside {rows[sy][sx]!r}'); bad += 1
    if rows[sy + 1][sx] not in '#':
        print(f'level {n}: nothing solid under the start'); bad += 1
print('PROBLEMS' if bad else 'all ten levels well formed')
